### ISSUE TITLE
[Question] Is it possible to map only a part of the background redux store to the proxy store?

### ISSUE THREAD

**Issue by prsidhu** [tshaddix/react-chrome-redux#103]
I have a very data-heavy extension and hence wish to share only the tab related data between background and proxy. My concerns are primarily performance related. Is it possible to accomplish that already?

**Comment by vhmth** [comment]
@prsidhu please have a look here:

https://github.com/tshaddix/react-chrome-redux/pull/100

Partial updates to the store are currently in code review.

Could you expand on what you mean by `data-heavy`? How much data are you proxying to/from your content scripts and the background process? What's your use case? Answering these questions may help us better understand the usage patterns that may emerge from adopters of this lib.

**Comment by prsidhu** [comment]
@vhmth Thanks for the reply. I'll check out those updates. My use case is as follows:

I have an extension that works on top of the customer messaging platforms like intercom, zendesk etc. It monitors the ongoing conversations and automatically suggests responses to customer service agents (through our AI). Agents can also manually search for queries. So each tab has multiple active conversations, which in turn can have multiple searches associated with them. I have, currently, implemented a custom redux pattern where app state and background store are handled by passing around constant string actions. I have to constantly monitor which conversation is open and then relay the data related to that conversation on that tab to render the UI accordingly. Also, I'm using a hash of tab_Id and conversation_Id to store the data. 

I was looking at this library for I wish to use a proper redux implementation and streamline my code base. I'm looking to have an object like:

activeConversations = { tab_Id: { conversation_Id: { } } }

and being able to map activeConversations[tab_Id] between the background and the content script would reduce the amount to data to be processed every time and also flatten the structure for the content script.

I hope this was helpful. Lemme know if you've got any doubts/suggestions for me.

**Comment by vhmth** [comment]
Ah, thank you for such a detailed explanation! The patched updates will definitely help your use case, but I can pretty much assure you that you won't run into huge scaling issues with that kind of model. I'm assuming most people won't have more than 100 or so conversations or queries going on at a time (and that's a real cognitive upper-bound). It's important to remember that message-passing happens via IPC pipes under the curtains, which are shared-memory buffers in V8. So it should be plenty fast (your computer does a lot more IPC over file descriptors off-disk all the time).

Right now we're handling quite a bit of data via message-passing in the [Loom](https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb) extension with no issues. I'm not actually sure if we handle more message-passing than y'all, but it will be interesting to see how this plays out. We have a per-tab state for our Gmail integration and have power sales users who have quite a few Gmail tabs open at a time who run into no issues.

Is it cool if I close this for the time being?

**Comment by prsidhu** [comment]
@vhmth Cool man. I'll give the library a shot. Thanks for the help

**Comment by seanders** [comment]
@vhmth Bit of a non-sequitur question. Could you point me to some documentation or resources regarding this: 
> It's important to remember that message-passing happens via IPC pipes under the curtains, which are shared-memory buffers in V8.

**Comment by vhmth** [comment]
@seanders not at all! Most IPC is over shared memory buffers when within the same sandbox as a general rule of thumb within the V8. At a lower level:

https://v8docs.nodesource.com/node-8.9/d9/d28/classv8_1_1_message.html#ad008582aa52dfdf703ed47e19ec01b60
https://v8docs.nodesource.com/node-8.9/d4/db8/classv8_1_1_shared_array_buffer.html

Here's some reference from Chromium (higher-level):

https://github.com/chromium/chromium/tree/master/ipc
https://github.com/chromium/chromium/tree/master/mojo

If you're asking how I know it is IPC, the answer is that it has to be. The background script and content script are in different processes. The background script runs in a long-lived process that endures for the entire browser session and the content script lives in the tab process which dies as soon as the tab is closed. To get these two processes to talk, you're necessarily doing IPC (interprocess communication). V8 and Chromium standardize IPC over shared memory zones as far as I know.
