### ISSUE TITLE
Can't use middleware

### ISSUE THREAD

**Issue by mfabre42** [tshaddix/react-chrome-redux#105]
Hello everyone,

I'm trying to figure how make a chrome extension... so I first started by doing a working webapp, and then I was planning to make it a chrome extension.

But as soon as i started, I face a major (or not) problem : i can't figure how to use middleware.

The doc say I can use middleware just like a classic redux store...

So I cloned the 'clicker-key' repo from react-chrome-redux-examples, make it works, and then I modified the index.js in event/src (so the background section) like this : 

```
import { createStore, applyMiddleware } from 'redux';
import rootReducer from './reducers';
import logger from 'redux-logger';

import { wrapStore } from 'react-chrome-redux';

const enhancers = applyMiddleware(logger);

const store = createStore(rootReducer, {}, enhancers);

wrapStore(store, {
    portName: 'example'
});
```

But for some reason, nothing is logged to the console ? Can somebody help here ? Since I have some others middleware to use...

Thanks :).

**Comment by vhmth** [comment]
@mfabre42 are you getting an error? Is the extension still working but nothing gets logged?

**Comment by mfabre42** [comment]
There is no error at all. Yes the extension is still working and the count doesn't start from 0 when I open a new tab or such, but nothing gets logged.

**Comment by vhmth** [comment]
What version of Redux is installed to that sub folder (`clicker-key`)? Seems like passing middleware as the third argument to `createStore` is for Redux >= 3.1.0:

https://github.com/evgenyrodionov/redux-logger#usage

**Comment by vhmth** [comment]
@mfabre42 sorry about the music in this video (you can mute) - didn't realize I had my mic setting on:

https://www.useloom.com/share/0dd42fdc487d492dbffcaefe1893ac49

But it seems to work for me. I included this video in case I did something differently.

**Comment by mfabre42** [comment]
Holy... didn't knew the background console was there... I was just inspecting the extension by right clicking on it and then "inspect". I had my others console.log working... but now that I try, not when I put them on the event part of the project...

Thank you, "knew" it was something stupid like this but wasn't able to figure it out. Thanks a lot, now I can do this extension the proper way.

**Comment by vhmth** [comment]
No worries @mfabre42. Closing this issue!
