### ISSUE TITLE
Resetting entire store state

### ISSUE THREAD

**Issue by benliger1987** [tshaddix/react-chrome-redux#107]
I'm trying to implement an action that resets the entire redux store state to it's default state defined in the individual reducers as per Dan Abramov's solution here [https://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store]. 

My setup is like so:

**background index.js:**

```
import {applyMiddleware,createStore} from 'redux';
import combineReducers from './reducers/index';
import {wrapStore,alias} from 'react-chrome-redux';
import thunk from 'redux-thunk';
import aliases from './aliases/aliases';

const combineAppReducers = ( state, action ) => {
  if ( action.type === 'LOG_OUT' ) {
    state = undefined;
  }
  return combineReducers(state, action)
}

const middlewares = [alias(aliases), thunk];

const store = createStore(combineAppReducers,applyMiddleware(...middlewares));

wrapStore(store, {
  portName: 'example'
});
```

**Reducers.js:**

```
import {combineReducers} from 'redux';
import userAuthReducer from './userAuthReducer';
import manageTeamsReducer from './manageTeamsReducer';

function lastAction(state = null, action) {
  return action;
}

export default combineReducers({
  userAuthReducer,manageTeamsReducer,lastAction
});
```
**EDIT**

The action is being toggled from one of the popup components like so:

`this.props.logout()`

This then fires off the below action:

```
export function logout() {
	return {
		type: 'LOG_OUT',
	}
};
```

I subscribe to the store in my component and can see the event being dispatched but it doesn't touch the state. My aliases are all firing fine for my various other functions such as logging in. 

I'm pretty sure i've followed his recommended setup like he suggests so not sure if this could be a potential bug?

**Comment by vhmth** [comment]
@benliger1987 have you verified that the aliases are being caught in the background script by opening and inspecting the background page?

**Comment by vhmth** [comment]
Also, where is the action/alias being triggered from (i.e. is it content/popup script context?). Could you provide that?

**Comment by benliger1987** [comment]
Updated in code above

**Comment by vhmth** [comment]
@benliger1987 do you have some sample code I can see? I finally understand what's going on, but I'd need to be able to debug with something tangible to dig in and see where there may be a bug in react-chrome-redux. First questions off the top of my head:

1. Is the `logout` action getting caught by the reducer fine?
2. If it is, what happens when I follow that action? Where does it return bad state?

If all else fails, for the time being, you can also subscribe to the logout action type in each of your reducers to reset the state.

**Comment by tshaddix** [comment]
Going to close this for now. @benliger1987 feel free to reopen if needed.
