### ISSUE TITLE
Performance decreases with number of open content scripts

### ISSUE THREAD

**Issue by corytheboyd** [tshaddix/react-chrome-redux#108]
I have noticed that when I have 30 tabs open that connect to the extension background, the performance decreases. I have experienced this exact scaling problem from previous work with chrome extensions with a similar architecture, and made the following changes:

1. Do not send messages from background to content script if the content script tab is not focused
1. When tabs come into focus, the background sends the entire state object to the content script since it will be behind.

Now, the only thing is this does require the `tabs` permission iirc, but this could be conditionally checked for before performing optimized behavior. Thoughts?

**Comment by vhmth** [comment]
@corytheboyd what is the perf decrease you're seeing? How quantifiable is it? The Loom chrome extension is fairly complex (many reducers, lots of recording options/state, cross-tab state with integrations on different pages like Gmail, etc.), and I keep about 20-30 tabs open at a time and have no problems running a recording on the Chromebook we test against in the office. To be fair, I suppose this heavily depends on the component hierarchy that reacts to state updates in the content script as well.

The beauty of this repo (and redux), IMO, is that you're guaranteed that every tab has the correct state regardless of whether it is focused or not. The state is global and easy to reason about. I'd rather not trade off that guarantee unless there's a pretty good, general use-case reason to do so. I'd at least make it an option that the developer has to opt into and make sure that option is heavily documented.

**Comment by corytheboyd** [comment]
Hey @vhmth 

I think I'll wait a little longer before worrying about performance. I am in the process of re-writing a legacy application and the component hierarchy isn't quite there yet. Furthermore, performance got much better after running the production build of the application, so yay!

I'll report back if I do run into issues. Thanks for the quick response!

**Comment by corytheboyd** [comment]
Going to close this for now.

**Comment by vhmth** [comment]
@corytheboyd great to hear that perf increased after some other tweaks/running prod version! Love when that happens. :-) We actually have some serious perf decreases when running Loom's backend stack locally due to Docker volume intrinsics. Always worries me before shipping to staging and making updates to critical service layers. :-P (probably means we need perf tests lol)
