### ISSUE TITLE
Updates to deep state not triggering connected component update

### ISSUE THREAD

**Issue by corytheboyd** [tshaddix/react-chrome-redux#109]
I noticed some strange issues after upgrading to 1.4.0. It appears as if making updates to deeply nested parts of my state object do not trigger updates to connected components in the UI. Here is an abridged version of one such perpetrator.

```javascript
// action
const setThing = value => ({ type: 'ACTION_TYPE', payload: value });

// selector
const getThing = state => state.nestedObject.thingValue;

// reducer
// ...
case 'ACTION_TYPE': {
  nextState.nestedObject.thingValue = action.payload;
  return nextState;
}
// ...

// component
@connect(
  (state) => ({ thing: getThing(state) })
)
class MyComponent extends Component {
  render() {
    const { thing } = this.props;
    return <span>{value}</span>
  }
}
```

In this example, `MyComponent` is not updated when the `setThing` action is processed and the store is updated. This worked fine in 1.3.3.

Sorry for reporting so many issues! Let me know if you need any further clarification. For now, I am going to stick to 1.3.3, but would love to take advantage of the partial updates.

**Comment by vhmth** [comment]
@corytheboyd YIKES! Seems like this is more than likely due to a change @jdolle introduced in #100. @tshaddix for the time being, should we roll back changes in `1.4.0`, branch those out, and then wait until we can figure this out to merge back in?

**Comment by vhmth** [comment]
Wait @corytheboyd I don' think the way you're mutating your nested state in that example, are you updating all of `nestedState`? That's technically the redux way of doing things (updating the whole state).

**Comment by vhmth** [comment]
Do you have an example full reducer file I can take a look at?

**Comment by corytheboyd** [comment]
All good, here is the gist of the full reducer:

```javascript
const initialState = {
  nestedObject: {
    thingValue: null,
  },
};

export default function root(state = initialState, action) {
  const nextState = { ...state };

  // ...
  case 'ACTION_TYPE': {
    nextState.nestedObject.thingValue = action.payload;
    return nextState;
  }
```

**Comment by jdolle** [comment]
@corytheboyd You are mutating the nested object. Keep in mind your state should be immutable.

```
const initialState = {
  nestedObject: {
    thingValue: null,
  },
};

export default function root(state = initialState, action) {
  // ...
  case 'ACTION_TYPE': {
    return {
      ...state,
      nestedObject: {
        ...state.nestedObject,
        thingValue: action.payload,
      },
    };
  }
  // ...
}
```

**Comment by jdolle** [comment]
Keep in mind what you are doing by setting `const nextState = { ...state };`. You are creating a _shallow_ copy. So internally, this allocates a new object, then copies over the values for each of your keys.
Those values are the exact same values that exist in `state`. This can be demonstrated by checking if `nextState.nestedObject === state.nestedObject`. The triple equal checks the object reference (which is an abstraction of a pointer -- it just tells us where the object exists).

**Comment by corytheboyd** [comment]
@jdolle Oh damn, you're totally right. Thanks for that pointer. I usually do this stuff with Immutable so was a bit rusty around the POJO approach. Thanks!

**Comment by corytheboyd** [comment]
Considering this one close.

**Comment by vhmth** [comment]
Woops way late on this one! Nice explanation @jdolle! I was afraid that was what was going on as well (hence the "are you updating all of nestedState?" comment). Glad this got sorted out!
