### ISSUE TITLE
React in library name?

### ISSUE THREAD

**Issue by viskin** [tshaddix/react-chrome-redux#11]
It seems that the library is completely free from being dependent on react. It can be used with say angular2+redux.
Any reason why it was named so?

**Comment by viskin** [comment]
Oh, OK.
I don't think renaming is a good thing to do. But I'm not sure. People already know your library by its name...
I think that sure thing to do is stating in README that it can work with react, angular or any other library. So folks that use angular2 will not be frightened to try it.

**Comment by tshaddix** [comment]
Great idea! I'll mark this as a suggestion.
