### ISSUE TITLE
Instagram chrome extension use react-chrome-redux

### ISSUE THREAD

**Issue by AllenFang** [tshaddix/react-chrome-redux#112]
👍 
https://github.com/CaliAlec/ChromeIGStory/blob/master/package.json#L26

**Comment by vhmth** [comment]
Awesome! :D And 851k users? That's impressive!

Would you want to add your logo/link to the bottom of the README? cc @tshaddix 

also relevant:

https://github.com/tshaddix/react-chrome-redux/pull/48

**Comment by AllenFang** [comment]
Hi @vhmth I just found that [ChromeIGStory](https://github.com/CaliAlec/ChromeIGStory) use this utility, it's not my repo :)  So I think you can add it by yourself 👍

**Comment by vhmth** [comment]
Ahhh I see. Thanks for the heads up Allen!

**Comment by paulius005** [comment]
Oh this is cool!

**Comment by tshaddix** [comment]
Very cool, @AllenFang ! Thanks for passing on.

If @CaliAlec confirms that he would like his extension included on the [readme section](https://github.com/tshaddix/react-chrome-redux#whos-using-this), then we'd love to add it. Going to close this for now :)

**Comment by CaliAlec** [comment]
I created a PR https://github.com/tshaddix/react-chrome-redux/pull/117

Thanks for the nomination @AllenFang and great work with this project @tshaddix and @vhmth

**Comment by tshaddix** [comment]
@CaliAlec Awesome stuff! Great project/extension to have on the list :)

Thanks again, @AllenFang !

**Comment by vhmth** [comment]
Thanks @CaliAlec & @AllenFang. This repo is all @tshaddix's work. I've just chimed in from time-to-time. :-P
