### ISSUE TITLE
Problem with store in injected content script

### ISSUE THREAD

**Issue by mateuszluczak** [tshaddix/react-chrome-redux#114]
Hello,

I love the idea of the project, however I have a little problem with correctly setting up the bindings to the store.

I am creating developer tools extensions and I have in my app: devtools page, content script that injects script into page to access it's scope and background script.

Here is my background script:
https://github.com/strudeljs/strudel-devtools/blob/master/src/background/background.js

Between background script and devtools I have successfully managed to establish connection and `store.ready` is fired (https://github.com/strudeljs/strudel-devtools/blob/master/src/frontend/app.js) so everything works cool there.

However, this is the code that I am using in the injected script (I am passing id of the plugin through the script tag from content script) - `store.ready` is never fired and any try of calling `dispatch` results in undefined `resp` object as a response to message.
https://github.com/strudeljs/strudel-devtools/blob/master/src/backend/backend.js

Am I doing something wrong or such a usecase is not supported by the library? Any help appreciated

**Comment by mateuszluczak** [comment]
Ok I was dumb and didn't know something like this is not possible.
I am using right now postMessages from the injected script and have redux in content script.

**Comment by vhmth** [comment]
https://www.useloom.com/share/bc5b50e798cb4c9d9db064ed5b4dc77c
