### ISSUE TITLE
Why not access the store directly?

### ISSUE THREAD

**Issue by rvolgers** [tshaddix/react-chrome-redux#115]
In a WebExtension project I am working on I take a different approach to integrating Redux. Instead of passing all actions and state through postMessage, I just access the Redux store directly. 

It is possible to access the background page's Window object directly from any extension page using `browser.extension.getBackgroundPage()` (using the WebExtension naming here, substitute `chrome` for `browser` if you aren't using the polyfill). If you set the Redux store as an attribute on the background page Window object you can get the Redux store as e.g. `browser.extension.getBackgroundPage()._reduxStore`. 

There are of course some concerns with naming since the Window object is a global namespace, but that is also an issue with the `portName` in the current `react-chrome-redux` implementation if I understand it correctly.

I still have a fake/proxy Redux state in the non-background pages because I do proxy the notification that the state has changed through postMessage (otherwise with many pages coming and going there is a risk of memory leaks through the store's subscriber list), but dispatch() and getState() are forwarded directly to the "real" Redux store that is fetched from the background page's window object. 

Is there any problem you can see with this approach? And if not, is this something that might be worth implementing in `react-chrome-redux`? The major advantage is of course that it prevents needless diffing, (de)serializing and copying of the state. 

One final note, I realise that this approach will not work for accessing the Redux store from content scripts. But in my opinion making the Redux store directly available to content scripts is a massive mistake anyway. That security boundary is there for a reason. For things that need access to the Redux store you can always inject an iframe with an extension page.

**Comment by tshaddix** [comment]
Hey @rvolgers! It's definitely a great alternative to the way we're currently doing things in react-chrome-redux. 

You also happened to answer your own question on "why" we do it the way we do: To include content-scripts in the party. Can you expand more on the "massive mistake" this is? Would love to hear more about what you may have found or additional insight

**Comment by rvolgers** [comment]
Just as a disclaimer, I have a background in computer security (which means I very much prefer clear and robust security boundaries) but I'm only just starting out with WebExtensions (which means I may not be familiar with various use cases). So YMMV, and "massive mistake" may not be the best way to communicate this. 

My concern is as follows:
1. Access to the Redux store is pretty powerful. For WebExtensions using Redux, access to the Redux store implies access to all the data used by the extension and likely provides indirect access to further API surface that is probably not meant to be robust against malicious input. 
2. Content scripts are loaded on untrusted sites. WebExtensions are likely to inject content scripts into untrusted or partially trusted sites (otherwise the functionality could probably be implemented into the website directly).
3. Content scripts are hard to secure. DOM injected by the content script cannot be relied on after its creation, event handlers cannot trust any data they take as input, as well as other gotcha's. As far as I understand this is one reason (besides practical reasons) why the content script context is less privileged than the full extension context.

So in short if you provide direct Redux store access to content scripts you are relying on store access not being abusable, or on the content scripts being coded securely. I don't feel particularly good about either of these assumptions.

For this reason I prefer a clearly scoped and locked down interface between the content script and extension context, which full access to the Redux store is not. 

Finally, here's some recent security vulnerabilities related to content scripts:

https://bugs.chromium.org/p/project-zero/issues/detail?id=1481&desc=3

https://bugs.chromium.org/p/project-zero/issues/detail?id=1217

**Comment by vhmth** [comment]
@rvolgers I'm not an expert in computer security, but wouldn't all the points you're making be a case _for_ using a port connection over accessing via `getBackgroundPage()`? The port object is likely implemented as a protected file descriptor within the VM of the browser, so I'm assuming you get access guarantees via stuff like virtual memory boundaries and the like. Actually, the manifest spec makes it so you have to explicitly state which domains have external access to content and the background of any extension, so it's likely built with security in mid.

Also, in my opinion, you should never store sensitive information in a redux store. Just as you probably don't want to store user secrets and sensitive information in something like Local Storage. I personally see this as a separate security concern and one that is up to the implementor (not a library that provides a mechanism to use Redux stores in a content script). It is up to the implementor to figure out whether they want access to the redux store via port objects using this lib and whether they should or should not be storing sensitive information in the store in the first place. It is also up to them to realize that absolutely nothing is safe/trusted on and from the client in the first place, especially in an extension.

All this being said, the performance gains of using `getBackgroundPage()` actually sound awesome though. What would you say the security concerns here would be using this from the content script? Why is having access to the store from the content script a problem in the first place? How would another script gain access to the store if the content script has access to it?

**Comment by neoncom** [comment]
My opinion:

- use backgroundpage for everything but content scripts, to maximize performance. Should be extremely easy to implement. I have a basic idea how it should be done just by looking at the code for 10min (and I just discoved this project today!)

- there are only two parties responsible for security
1. chrome dev team who restrict what can be done with the API
2. the actual extension dev

The react-chrome-redux time should maximise the possibilities given to them by the chrome dev team. The extension dev ultimately has to decide what his extension does with it. Just IMO.

**Comment by arogg** [comment]
My opinion:

- use backgroundpage for everything but content scripts, to maximize performance. Should be very easy to implement. I have a basic idea how it should be done just by looking at the code for 10min (and I just discoved this project today!)

- there are only two parties responsible for security
1. chrome dev team who restrict what can be done with the API
2. the actual extension dev

The react-chrome-redux team should maximise the possibilities given to them by the chrome dev team. The extension dev ultimately has to decide what his extension does with it. Just IMO but seems very logical if you think about it. Otherwise the user would just implement everything with getBackgroundPage() on his/her own anyway.  Before redux I did just that. The only people who can and should actually enforce security (each on different levels) for an extension are those 2 factions named above.

**Comment by arogg** [comment]
I should note that performance easily becomes critical for a redux app, in general. I'm looking to dispatch progressbar progress to the store (involves many updates, sure i could throttle it, but non the less..). Nothing unusual. Also I see the shallowDiff method that is being used. 2 issues with that:
- shallow diff is fast, but many updates deep in the state tree still means potentially lots of data transferred
- a deep diff would mean less data transferred but the diff calc would be slower
So using backgroundpage for non-contentscripts would be nice.

**Comment by rvolgers** [comment]
I just wanted to give an update here, to not leave things hanging from my end.

Adding support for using the background page to react-chrome-redux would increase the complexity of this library, and having two different code paths to access the store could lead to confusion. For one example, using ImmutableJS or other custom objects in the store would work from the background and extension pages but not from content scripts. Also the diffing might introduce subtle behavior differences. I'm not convinced it's worth it just for performance gain. 

Writing an equivalent to react-chrome-redux that has unconditional support for ImmutableJS and does not support content scripts seems like the right path for my use case. The code ends up being very simple because it does not have to do any diffing and serialization, and what's more I basically already have all the  code working (just not as nicely factored as react-chrome-redux, as it was intended to be a temporary fix while we figured out the correct approach). 

So I will not be pursuing this issue further personally. If our trivial react-chrome-redux equivalent ends up being open sourced I'll give a heads up here, so people can find it if they need it.

**Comment by tshaddix** [comment]
@rvolgers Thanks for giving an update here and also starting this discussion. I think it's a really good one to have.

Side note: Would love to see your solution if you do make it available!

**Comment by vhmth** [comment]
Yeah I definitely would love to see an update here if you come up with one @rvolgers. Agreed 2 code paths with accessing bg page vs. message passing would be ugly, but it's all transparent to the end-user. I'd see it as "get the bg page if you can, otherwise, try message passing".

Either way good luck and keep us posted!

**Comment by vhmth** [comment]
@rvolgers I'm closing this since it seems like there won't be any progress based on your comment and no one else seems invested in etching a path here. Feel free to reopen!
