### ISSUE TITLE
Serialization hooks for Dates

### ISSUE THREAD

**Issue by ethanroday** [tshaddix/react-chrome-redux#125]
First of all, love this library! Was looking at a custom solution but then came across this and no doubt saved many many hours.

I've noticed that when my background store has `Date`s, they surface as empty objects in the proxy store. It looks like this is a limitation of Chrome's message passing, not of this library per se, but it was a little mystifying when I first encountered it. In retrospect, it shouldn't have been, since `Date`s are not primitives or plain objects, but it may be worth at least adding a note in the documentation reminding users to store dates as epochs.

Alternatively, it may be worth considering one of the following:
- Explicitly serialize dates before message passing and then parse them on the other end.
- Since Chrome message passing is serializing to strings anyway, just stringify the payload before sending and use a custom parser on the other end to recover the dates.
- Expose hooks for users to specify their own serializers/parsers.

The last option seems like it would be fairly low-effort. I can attempt a PR if desired.

**Comment by ethanroday** [comment]
See #126.

**Comment by vhmth** [comment]
@ethanroday thank you for looking into this! Going to look at this PR today. Appreciate your contribution!
