### ISSUE TITLE
Errors related to Chrome Canary (v67) implementation changes to chrome.runtime.connect and chrome.runtime.sendMessage

### ISSUE THREAD

**Issue by marcokam** [tshaddix/react-chrome-redux#134]
It looks like the way Store.js is calling `chrome.runtime.connect` and `chrome.runtime.sendMessage` causes errors in Chrome v67.

These errors include:
1) Calling `connect` and `sendMessage` with a blank extension id no longer works.
2) Calling `sendMessage` without passing `null` for the optional `options` third parameter no longer works.

The [documentation](https://developer.chrome.com/apps/runtime#method-connect) states that the extension id parameter is an optional string, which probably means that it should either be the extension id string or null/undefined.  I've tested that using a blank string works in:
Version 65.0.3325.162 (Official Build) (64-bit) and
Version 66.0.3359.33 (Official Build) beta (64-bit)

However, it stops working on the Canary build I have installed:
Version 67.0.3375.0 (Official Build) canary (64-bit)

I've logged a bug on the chromium project here, in case there are other libraries that may do the same thing.
https://bugs.chromium.org/p/chromium/issues/detail?id=823577

I think that we should probably change the code in Store.js as it is a simple change to set the default to be `null`.

The other issue has to do with how Store.js is calling chrome.runtime.sendMessage.  At the moment it is being called with 3 parameters.  However, the [documentation](https://developer.chrome.com/apps/runtime#method-sendMessage) describes an optional `options` third parameter.  I've confirmed that the current code breaks in Canary as well.  Adding a `null` for the third parameter fixes it.

I've also confirmed that both these changes (null for extension id and adding a null third parameter) still work in v65 and v66.

I'm currently preparing a PR to fix these issues.  We should probably do more testing on other projects as well as earlier chrome versions to make sure this is still working properly.  According to Chrome's release schedule, v67 won't be released until the the end of May, so there is some time before this becomes a production worry:
https://www.chromium.org/developers/calendar

**Comment by tshaddix** [comment]
@marcokam Thanks for reporting this and also submitting a PR! Looking through it now.
