### ISSUE TITLE
How easy is it to use this library for Chrome extensions?

### ISSUE THREAD

**Issue by teckays** [tshaddix/react-chrome-redux#14]
As of now, playing few days with this library I've found it a bit tricky to use. 

**1. Let's assume I want to inject a button somewhere on the page:**
 - original DOM
```
<nav class='menu'>
    <a href="?">First</a>
    <a href="?">Second</a>
    <a href="?">Third</a>
</nav>
```  
 - element to be injected
```
<a href="?">Fourth</a>
```

because of the way React works, it's not possible to simply render my own component inside `nav.menu` because it's going to replace everything inside. So what I would have to do is to wrap my component in a new DOM element:
```
render(<MenuItem />, document.getElementById('item-anchor'))

<nav class='menu'>
    <a href="?">First</a>
    <a href="?">Second</a>
    <a href="?">Third</a>
    <span id="item-anchor">
        <a href="?">Fourth</a>
    </span>
</nav>
```

**2. How to render multiple instances of the same component with some data from an API?**
 - original DOM
```
<ul>
    <li>
        <span>Text</text> // the text of this item should be replaced with some data from ajax
    </li>
    <li>
        <span>Text</text> // the text of this item should be replaced with some data from ajax
    </li>
    <li>
        <span>Text</text> // the text of this item should be replaced with some data from ajax
    </li>
</ul>
```

let's say I create a react component for this:
```
// TextComponent
... 
render () {
    return (
        <span>{this.props.text}</span>
    )
}
```

how to actually render my above component multiple times and by passing in the `text` prop returned from the API?

I have the `index.js` file that does
`render(<TextComponent text={this.store.response[i]}/>, );` I can't iterate in the component because the items to be rendered are not siblings, nor I can iterate in `index.js` and call `render()` multiple times and passing in the text from an array.

In my opinion it works OK for apps an popups, because you are in full control of the DOM you create and therefore you can encapsulate everything nicely. However, with injecting content into the page, where you have to inject multiple elements here and there, it makes it too difficult to handle in my opinion, but I hope I'm wrong on this, so please ... any thoughts would be much appreciated.

**Comment by tshaddix** [comment]
Hi @teckays! Sorry to hear you're running into trouble. 

Both of the issues you are running into seem to be inherently tied to React, and not this package. [This package has no reliance on React, despite its name](https://github.com/tshaddix/react-chrome-redux/issues/11). You can use any UI library you want (or none!) with Redux as well as this library.

We use React with Content Scripts at [GoGuardian](https://goguardian.com) with little trouble, but that's because our use-case is better suited for React.
