### ISSUE TITLE
Chrome extension issue in block-chain transaction

### ISSUE THREAD

**Issue by jasham** [tshaddix/react-chrome-redux#145]
Basically I want a chrome extension which takes data from block-chain and display in chrome content-script also when user click on that data one transaction happen which will increase the count in block-chain.

I am able to retrieve data from block-chain please check the below code.

```
async componentDidMount(){
    const ads = await advertiserAbi.methods
                     .getSpecificAdvertiserDetail(
                     "any address").call();
    this.setState({ads});
}
```
But the problem is coming in performing transaction. Please check the below code.

```
async onSubmitForUpdate() {
    console.log("Hello");
    await userAbi.methods
      .setStatistics("any address")
      .send({
      from: "any address"
    });
}
```

Below is the error which I am getting when checked in console.

`POST https://rinkeby.infura.io/<--specific address--> 405 ()`

```
Uncaught (in promise) Error: Invalid JSON RPC response: ""
at Object.InvalidResponse (content.js:108391)
at XMLHttpRequest.request.onreadystatechange (content.js:119211)
```

**Comment by Quaiks** [comment]
Review [Infura docs](https://infura.io/docs). This is not a problem with `react-chrome-redux`

**Comment by tshaddix** [comment]
Hi @jasham . Agreed with @Quaiks . This looks to be an issue outside of react-chrome-redux.

**Comment by jasham** [comment]
Thanks @Quaiks & @tshaddix. I have checked the issue is with Infura because it does not support eth_sendTransaction.
