### ISSUE TITLE
proxy store does not update for a numeric state 

### ISSUE THREAD

**Issue by skk2142** [tshaddix/react-chrome-redux#147]
It seems like the proxy store does not update when the state of the redux store has a numeric state i.e. 
```javascript
const rootReducer =  (state = 0, action) => {
  switch (action.type) {
    case 'INCREMENT':
      return state + 1;
    default:
      return state;
  }
}

export default rootReducer
```

To fix this, I changed the state to an object by wrapping the reducer using:
```
export default combineReducers({
  count: rootReducer
})
```
It works as expected with this reducer.

**Comment by vhmth** [comment]
Hmm strange we should probably support this base case since serializing state is just `JSON.parse/stringify`. Did you happen to catch the error logged or did it just silently fail @skk2142?

**Comment by DJWassink** [comment]
Can confirm that it also doesn't work for `null` or `false`, probably all values which are falsy are ignored. (silently btw)
