### ISSUE TITLE
Error in event handler for (unknown): TypeError: Cannot read property 'error' of null

### ISSUE THREAD

**Issue by lmenus** [tshaddix/react-chrome-redux#149]
Hello,

I will make a reference to this older [thread on StackOverflow](https://stackoverflow.com/questions/41379879/typeerror-cannot-read-property-error-of-undefined-on-react-chrome-extension) as that's the only discussion I could find. I was trying to discover what's happening for a long time, but no luck so far.

I am dispatching a function from a component, `dispatch(me('hello'))`.

`actions/me` has a simple action.

```js
export const me = message => ({
  type: 'ME',
  message,
});
```

And a simple reducer.

```js
case 'ME':
  return {
    ...state,
    message: action.message,
  };
```

So far so good. I placed logs just about everywhere and the action gets dispatched, everything works, but.

`console.log(dispatch(me('hello')));` will tell us `Promise {<pending>}`. Wait, what? Yes, this is because the action is dispatched from a content script. Had this been dispatched from a background script, we'd get back `undefined` as expected. So the question is, how do we fix this issue? Should we let the background script dispatch all actions?

**Comment by vhmth** [comment]
Woops closed by accident.

The reason you’re getting a promise is because dispatching actions against a wrapped store in a content script actually ferries that action to the background script where the single source of truth store lives. All updates to that store on the background get serialized back to the content scripts so the wrapped stores there stay in-sync.

Basically, the promise returned when dispatching from a content script gets resolved when the background script receives the action since that communication mechanism is async. I’m all for standardized/consistent APIs, but I push to keep the returned promise since that can be useful in many cases (especially if there are additional async things that get done in the background because you’re dispatching an alias).

**Comment by lmenus** [comment]
Hi @vhmth, thank you for looking into this! What I am trying to resolve is, what should be done about this, if anything at all? Is it an anti-pattern to dispatch actions from content scripts? If not, that error we keep getting is not very useful as it doesn't identify the reason. In addition to that, it doesn't appear to break any functionality (as long as you don't rely on synchronously returning some value), so it seems unnecessary. I could dispatch actions from the background script only to prevent the error, but is that the recommended way?

**Comment by vhmth** [comment]
@lmenus could you provide a simple example of how you're getting an error? From the description of your issue, it seems like all is good and it's just the return type that's tripping you up. I'm trying to pinpoint the exact problem here, and, often times, a minimal test case is useful.

**Comment by lmenus** [comment]
@vhmth I'll try to create a sample extension in the next few days if description won't be sufficient, though I hope we can do without it! The thread I linked to has [this answer](https://stackoverflow.com/a/41775912/4934026) which is exactly what happens in my case. Unlike the OP on StackOverflow, my script works properly (error has no impact on the app), hence I believe it could be an issue with `react-chrome-redux` or me using an anti-pattern.

The actual dispatch type that causes this error is in `lib/constants/index.js` on line 8.

Then in `lib/wrap-store/wrapStore.js` on line 61 we get back `undefined`...

```js
  /**
   * Respond to dispatches from UI components
   */
  var dispatchResponse = function dispatchResponse(request, sender, sendResponse) {
    if (request.type === _constants.DISPATCH_TYPE && request.portName === portName) {
      var action = Object.assign({}, request.payload, {
        _sender: sender
      });

      var dispatchResult = null;

      try {
        dispatchResult = store.dispatch(action); // <- equals undefined
      } catch (e) {
        dispatchResult = Promise.reject(e.message);
        console.error(e);
      }

      dispatchResponder(dispatchResult, sendResponse); // <- send undefined
      return true;
    }
  };
```

...which causes `lib/store/Store.js` error on line 203.

```js
  {
    key: 'dispatch',
    value: function dispatch(data) {
      var _this3 = this;

      return new Promise(function (resolve, reject) {
        chrome.runtime.sendMessage(_this3.extensionId, {
          type: _constants.DISPATCH_TYPE,
          portName: _this3.portName,
          payload: data
        }, function (resp) { // <- still undefined :(
          var error = resp.error, // <- Error in event handler for (unknown): TypeError: Cannot read property 'error' of null
              value = resp.value;


          if (error) {
            var bgErr = new Error('' + backgroundErrPrefix + error);

            reject((0, _assignIn2.default)(bgErr, error));
          } else {
            resolve(value && value.payload);
          }
        });
      });
    }
```

But why does this happen? I logged line 112 in `lib/wrap-store/wrapStore.js` which is here.

```js
  /**
   * Setup action handler
   */
  chrome.runtime.onMessage.addListener(dispatchResponse);
```

When everything runs OK, `dispatchResponse()` would receive the first parameter `request` that looks like this.

```js
{
  someKey: 'someValue',
  anotherKey: 'anotherValue'
}
```

When we get the error (when I dispatch an action from content scripts), our request looks like this.

```js
{
  payload: {
    type: "<redux action type>",
    actionKey: 'someActionValue'
  },
  portName: "<port>",
  type: "chromex.dispatch"
}
```

So we end up with the action object in the payload. Again, I will create a sample test case if this doesn't clarify it, please let me know.
