### ISSUE TITLE
Initial popup launch problem

### ISSUE THREAD

**Issue by n3vrax** [tshaddix/react-chrome-redux#152]
This is probably related to PR #111 

It happens to me when first starting chrome. Hitting the browser action I get an empty popup. On subsequent clicks it works, and I'm not able to reproduce it again even if I'm reopening chrome. It happens only after I open the PC, just once. Also, when installing the plugin, it works, so it is a bit hard to reproduce normally

My suspicion is that the store.ready().then doesn't get resolved, but I have no idea why this behavior

My setup is as follows. I use non-persistent background script

#### popup
```javascript
const store = new Store({
    portName: env.STORE_PORT_NAME
});

const authService = new AuthService();

store.ready().then(() => {
    ReactDOM.render(
        <Provider store={store}>
            <AuthContext.Provider value={authService}>
                <MemoryRouter>
                    <App />
                </MemoryRouter>
            </AuthContext.Provider>
        </Provider>,
        document.getElementById('root')
    );
});
```

#### background
```javascript
//....

const initialState = () => ({
    authentication: {}
});

/**
 * Initialize state from chrome storage
 */
chrome.storage.local.get(['state'], function (result) {
    let state = result.state !== undefined ? result.state : initialState();

    const store = createStore(rootReducer, state);
    store.subscribe(() => {
        chrome.storage.local.set({state: store.getState()});
    });

    wrapStore(store, {portName: env.STORE_PORT_NAME});

    ReactDOM.render(
        <Provider store={store}>
            <Background/>
        </Provider>,
        document.getElementById('root')
    );
});
```

**Comment by n3vrax** [comment]
Coming back with a possible idea why this is not working
Possible because I have the wrapStore inside the chrome storage callback, so the background script is async

Any workarounds?

**Comment by vhmth** [comment]
@n3vrax what if you were to rework your code to be like this? I would strongly suggest that you initiate the background store as soon as you can in all cases:

```
//....

const store = createStore(rootReducer, {
  authentication: {}
});

wrapStore(store, {portName: env.STORE_PORT_NAME});

ReactDOM.render(
    <Provider store={store}>
        <Background/>
    </Provider>,
    document.getElementById('root')
);

/**
 * Initialize state from chrome storage
 */
chrome.storage.local.get(['state'], function (result) {
    if (result.state) {
      store.dispatch(...some action to replace whole state);
    }

    store.subscribe(() => {
        chrome.storage.local.set({state: store.getState()});
    });
});
```

**Comment by n3vrax** [comment]
Hey, there's been a long time, I forgot about this thread.
I think you can close this. I ended up doing as you suggested, and it seems to work fine for now.

Thanks!
