### ISSUE TITLE
Lag in Connect Time for Proxy Store?

### ISSUE THREAD

**Issue by vhmth** [tshaddix/react-chrome-redux#16]
I have a minimal project running where there are a couple of reducers with default values running in the background. I use `wrapStore` immediately in the background script and immediately set up a proxy store via the `Store` constructor in my popup window. I noticed that this leads to an empty object state in one of my container components (when `mapeStateToProps` is called on it). If I set a `100ms` timeout before rendering my `<PopupApp>` surrounded by `<Provider>` with the proxy store set to it, everything works.

Seems like there may be a race condition? Should I be listening for an event so I know the proxy store has established its connection correctly? Seems like [onConnect](https://developer.chrome.com/extensions/runtime#event-onConnect) is a good candidate and the proxy store object should emit some sort of event when the connection has been made and the initial state is filled in?

**Comment by tshaddix** [comment]
Check [this](https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage#initializing-ui-components) out and let me know if it helps :)

**Comment by vhmth** [comment]
This totally helps! Thank you man. Totally blanked on the "Docs" section at the bottom of the README. Closing this!

**Comment by tshaddix** [comment]
@vhmth Awesome :)
