### ISSUE TITLE
extension update flow

### ISSUE THREAD

**Issue by pelegb** [tshaddix/react-chrome-redux#167]
Hi,
I've been using your package for the past couple of weeks and I've enjoyed it a lot. Thanks for the great package.

I am trying to understand what do I need to do inorder to handle upgrades via the Chrome Web Store. My content script is injected into a long lived tab (Gmail) and so after the upgrade which causes a chrome.runtime.reload() the port is closed and according to my review of the proxy store code there is not handling for this case. I can re-inject the content script but the old one still dispatches actions to the broken pipe.

I'm a noob to chrome extensions, so any assistance will be greatly appreciated.
Thanks

**Comment by tshaddix** [comment]
@pelegb Ah yes - this is a super interesting scenario. Your extension context is invalidated for the original content script when you update. It's a really messy thing that chrome doesn't elegantly handle for you.

One thing you could do is ask the user to reload the page when your content-script loses a connection. You could also automatically reload the page when your extension updates (after a quick confirmation from the user).

Other than that, I'm not perfectly sure what else you can do as your orphaned content script is inaccessible at that point.

**Comment by craigsketchley** [comment]
I was going to ask something similar to this. I'm wondering where/how we could handle or catch a lost background connection in a content script?

Great library by the way :+1:

**Comment by tshaddix** [comment]
Thanks, @craigsketchley!

[This bug comment](https://bugs.chromium.org/p/chromium/issues/detail?id=649947#c16) seems to indicate that you can listen for a disconnect on the port.

Have you tried that? I can give it a whirl this weekend.

**Comment by pelegb** [comment]
As described in the issue, I've re-injected the content script and left the old one as a zombie
