### ISSUE TITLE
Need help to use the data that is stored just before on the redux thunk action

### ISSUE THREAD

**Issue by xpdlf1004** [tshaddix/react-chrome-redux#179]
Hi, I'm using the redux thunk and background script for storing the redux data.
And I'm implementing the web version and chrome extension at once.
Below code is working well on the web application, but not on the chrome.
```
const fetchData = () => {
    return async(dispatch, getState) =>{
        dispatch({
            type: "SAVE_DATA",
            data: "data"
        });
        dispatch(calculateSomethingUsingSavedData());
    }
}

const calculateSomethingUsingSavedData = () => {
    return async(dispatch, getState) => {
        const savedData = getState().store.savedData;
        ... use saved Data
    }
} 
```
I think there is no data at the time the savedData is called because this library asynchronously stores the data to the background script. 
How can I solve this problem?

**Comment by xpdlf1004** [comment]
For the temporary,
I added a setTimeout function for calculating it after saved to the store
```
setTimeout(() => {
                dispatch(calculateSomethingUsingSavedData());
            }, 100);
```

**Comment by tshaddix** [comment]
Ah - is this on the proxy store in your UI components?

**Comment by kaglowka** [comment]
I believe that contrary to the classical Redux store, every dispatch (not only thunk etc.) returns a promise.
(source [here](https://github.com/tshaddix/react-chrome-redux/blob/32271d2c017aea8374762984a97405d2f3724976/src/store/Store.js#L138) ).
You probably can just wait for the promise with `dispatch(...).then( ... )`.

Btw this would be one more way -- beside aliases -- this store differs in respect to the original Redux store (where non-promise synchronous dispatches do take place). It might be useful to add it to the docs for completeness (some kind of "migrating from pure Redux" section). I'd be happy to do that

**Comment by tshaddix** [comment]
@kaglowka You're right! Because the dispatches are actually being proxied to the backend store via message-passing, they are actually asynchronous which is why we return a promise.

If you're down to add to the docs, it would be very appreciated :)

**Comment by xpdlf1004** [comment]
Oh, got it :)
I did not know that dispatch returned the promise. Maybe I can solve it. Thank you 👍

**Comment by tshaddix** [comment]
@xpdlf1004 Sounds great! Let us know if that doesn't work and we can reopen this issue.
