### ISSUE TITLE
Content Store is not getting a response value from sendMessage

### ISSUE THREAD

**Issue by vhmth** [tshaddix/react-chrome-redux#18]
I noticed that for some actions that get dispatched via `mapDispatchToProps`, I'm getting the following error:

```
TypeError: Cannot read property 'payload' of undefined
```

This error pops up [here](https://github.com/tshaddix/react-chrome-redux/blob/master/src/store/Store.js#L74). I'm opening this in case anyone could possibly think what the issue may be, but I'm investigating.

Note: I'm using `redux-thunk` and frequently dispatch functions instead of action values with a `type`, but that shouldn't be an issue. I just thought I'd leave that note here in case it may be useful to debug.

**Comment by vhmth** [comment]
An update. Looks like both problem actions are actually aliases. The response is:

```
{ error: null }
```

**Comment by vhmth** [comment]
Seems like I've figured it out. This happens when I don't return a `dispatch` within a redux-thunk function. For instance, if I have a thunk as follows:

```
export const someActionCreator = () => {
  return (dispatch, getState) => {
    if (<some_condition>) {
      return;
    }
    return dispatch({ type: SOME_ACTION });
  };
};
```

That premature `return` raises the error in this issue. If I swap it out with `return dispatch({ type: '' });`, it seems to work. This is strange though, and it seems like it's completely kosher to not dispatch (conditional dispatches) from within a thunk (unless I'm mistaken about that - I am still pretty new to redux).

**Comment by tshaddix** [comment]
So the issue seems to relate to the default `promiseResponder` [here](https://github.com/tshaddix/react-chrome-redux/blob/master/src/wrap-store/wrapStore.js#L18). If you don't call dispatch, then it looks like the result is returned as undefined (makes sense). I'm adding a simple work around now. Watch for a PR in the next couple minutes.

**Comment by vhmth** [comment]
Awesome thank you @tshaddix! Appreciate the quick response!

**Comment by tshaddix** [comment]
This will be included in `0.0.8`. Building release now.

**Comment by vhmth** [comment]
💃

**Comment by tshaddix** [comment]
Done! Thanks for reporting, @vhmth !

**Comment by vhmth** [comment]
https://www.opentest.co/share/a54ffc8059c911e6a1ffdd04f7a207b4

**Comment by tshaddix** [comment]
Sounds great! I'll be in SF in a couple weeks.

Also, sweet extension. Wonderfully clean experience!
