### ISSUE TITLE
Using with Router

### ISSUE THREAD

**Issue by rhoman** [tshaddix/react-chrome-redux#21]
Hi,

have you tried using Routing along with this?
And if so, did you wrote your own Router or used existing one (like react-router, redux-router, reacr-router-redux, etc.).

I'm looking mostly for authorization solution.

Best, 
Martin

**Comment by tshaddix** [comment]
Hi, @rhoman!

I rolled my own basic router when I first started using React/Redux in a Popup. It simply had a state property called `route` with `path` and `params` properties and a basic Router component.

That said, you should have no issues with using react-router and other packages like it with Chrome Extensions and Apps. Chrome Extension and Apps all sit under a `chrome://...` domain and have the same characteristics of a webpage. 

To test this, I just opened up a popup on one of my extensions and used Chrome DevTools to print out and modify the location. Check it out:

<img width="641" alt="screen shot 2016-08-09 at 9 57 10 am" src="https://cloud.githubusercontent.com/assets/2173532/17525485/b6b7a75a-5e17-11e6-8d2a-7a245b7361ad.png">

Although I haven't actually tried using any of the routing packages inside an extension, this leads me to believe it should be no problem!
