### ISSUE TITLE
State not Updating Properly after Page Refresh?

### ISSUE THREAD

**Issue by vhmth** [tshaddix/react-chrome-redux#23]
What's up Tyler. This issue may be due to my limited understanding exactly how `react-redux` should work, but here's what's happening:

1. Create recording.
2. UI gets updated.
3. End recording.
4. UI gets updated to be removed.

This is the proper behavior for our extension. When I do this:

1. Create recording.
2. UI gets updated.
3. Refresh page.
4. UI comes back to proper state.
5. End recording.
6. UI is not removed.

The UI is not removed and in fact a nested component that shouldn't be getting rendered does and its `mapStateToProps` function is getting called (which is throwing an error). I made a recording showcasing the bug with our tool:

https://www.opentest.co/share/d07eab70645c11e69680a3b55516ed77

Not sure what could be the cause, but I'm game to look into this today since this is kinda a high priority for us to fix.

**Comment by tshaddix** [comment]
Hey, @vhmth. Sorry for being MIA the last couple days. I've been traveling.

I'll try to take a look at this as soon as I get a free moment.

**Comment by vhmth** [comment]
No worries at all @tshaddix. Was wondering if you had any idea what might be going on off the top of your head so I could look into it too. Will let ya know if I find anything.

**Comment by vhmth** [comment]
So gave this a bit more thought - perhaps it's the order the listeners are fired in `Store.js`:

```
this.listeners.forEach(function (l) {
  return l();
});
```

Here's my theory:

On first page load, I have a `ContentApp` component which determines whether or not to render the nested recorder. The nested recorder isn't rendered immediately when there isn't a recording going on, so it and its children do not have listeners attached to the store via `connect`.

When you refresh the page however or start the app in a state where the nested components are rendered, those nested component `subscribe` calls somehow get ahead of the listener for the top-level component which is why their `mapStateToProps` function is called before the top-level component is able to remove those components.

Not sure how this would even be possible looking at the code, but I'm gonna see if I can figure it out.

**Comment by vhmth** [comment]
Just added a `console.log` in the `subscribe` method of the `Store` object and can confirm that a nested component's listener is indeed at the head of the array. So I believe its `mapStateToProps` will get called before other components. Diving deeper.

**Comment by vhmth** [comment]
Dove into `react-redux` a bit and can see that `trySubscribe` which does the actual subscription to the store is pretty dumb (as in simple). It simply tries to subscribe at `componentDidMount`. I'm going to `console.log` at each `mapStateToProps` in my component hierarchy and compare them before and after a page refresh.

**Comment by vhmth** [comment]
So I've logged the component in each `mapStateToProps` function. For context, the hierarchy of the components is as follows:

[`<ContentApp>`] -> [`<PersonalRecorder>`] -> [`<BubbleMenu>` | `<Camera>`] -> [`<BubbleMenuXItem>`]

It looks like the calls are getting called in the same order from a fresh load vs. after a refresh:

**Fresh Load**

![first load](https://cloud.githubusercontent.com/assets/603426/17754690/9e79d112-648a-11e6-9393-0c74139c94e8.png)

**Load after Refresh**

![load after refresh](https://cloud.githubusercontent.com/assets/603426/17754693/a3d71322-648a-11e6-8668-0935556dc115.png)

Ending a recording also looks the same except it seems like `<Camera>` gets called  again after `<PersonalRecorder>` which is strange. This is also where I'm seeing the error being thrown in `mapStateToProps` since that component shouldn't be rendered at that moment and I'm expecting the shape of the state to be different in it:

**End Recording with No Refresh**

![end recording with no refresh](https://cloud.githubusercontent.com/assets/603426/17754730/cb2ed22a-648a-11e6-9228-540d970e9c85.png)

**End Recording with Refresh**

![end recording after refresh](https://cloud.githubusercontent.com/assets/603426/17754735/d175a5b4-648a-11e6-9353-b50592778703.png)

**Comment by tshaddix** [comment]
@vhmth Thanks for all the detailed documentation. I'm still having a bit of trouble following along as I don't have the source to tinker with. Looking forward to hearing your findings.

**Comment by vhmth** [comment]
Yeah not 100% sure what's going on yet. The general gist is:

1. Create sample chrome app that toggles some UI component when the browser action is clicked.
2. Make sure the UI component has nested container components created via `connect`.
3. Toggle to render UI.
4. Refresh.
5. Toggle to remove UI.
6. Observe that the the nested components are getting updated with the new state even though they're supposed to be removed.

I was looking through the code here as well as `createStore` in Redux and noticed that you are setting up your own plain store for the content script `Store` objects.

Is there any reason you went with that approach vs. creating an internal redux store via `createStore` and adding some middleware to it that handles the proxying to/from the background script? Trying to figure out what pitfalls we may run into by delegating most of the core store logic to `createStore` from Redux and conforming to what their middleware API may be.

**Comment by vhmth** [comment]
Update:

This works even if I have a singly-nested component. Will try to make a standalone repo that showcases what's going on so you can take a look too @tshaddix.

**Comment by vhmth** [comment]
Hey @tshaddix I've created a very simple repo that showcases how to reproduce the bug. If you check the README, there is a video link there with how to get up and running and exactly what to look for:

https://github.com/vhmth/react-chrome-redux-bugs

**Comment by tshaddix** [comment]
@vhmth Cool thanks for doing this!

To answer your question:

> Is there any reason you went with that approach vs. creating an internal redux store via createStore and adding some middleware to it that handles the proxying to/from the background script?

I tried to keep the components as simple and single-purpose as possible. Redux stores do a lot of excellent things with reducers and middleware to build a final state, but we don't need any of that on the UI Component side. We already have the final state from the background store, so why use a full Redux store when you just need a basic Proxy to fulfill the same API?

That was my logic at the time, anyways :)

**Comment by vhmth** [comment]
No worries - that makes sense. That's how I'd build it too. :-) Was just curious if there were other reasons.

So I `console.log`'d in `mapStateToProps` for each component in the sample app and it seems like after a page refresh the `mapStateToProps` of the subcomponent gets called before its parent. Very strange. That's definitely the issue here - trying to figure out why/how that's happening from `react-redux`'s point of view. Since the store here is very simple, maybe it's a quirk that we're not catching/hasn't been documented?

**Comment by tshaddix** [comment]
Yep I just ran it on my end and was able to reproduce the bug.

I've never run into this myself mostly because I stick to the [smart/dumb component philosophy](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.jjay4rmsk), which limits the amount of `connect()` calls you can have in parent-child relationships (only container components should have connect calls).

Regardless, that doesn't solve this bug. I'm not convinced this is a react-chrome-redux bug as the `ProxyStore` implements the exact same API as a `redux` store. A redux store does not pick and choose what parts of the state it's going to present last time I checked. It just dumps the entire state to all listeners. How that information actually gets distributed is up to `react-redux`.

[I checked](https://github.com/reactjs/redux/blob/master/src/createStore.js#L176) to make sure there was nothing weird about the order in-which a redux store fires subscribe listeners. It looks like we do it the same way (in order).

**Comment by vhmth** [comment]
I think I mechanistically understand what's happening.

`react-redux`'s `connect` component will try to subscribe to the store at `componentDidMount`. Since `componentDidMount` gets called from children up the component hierarchy to their parents, nested `connect` components will get state updates before their parents since they subscribe to the store first. This only happens after a refresh in this case because, without the refresh, the sub component isn't initially rendered in my demo app (and the Opentest app).

**Comment by tshaddix** [comment]
That's dead-on to what I'm seeing in the example repo you have. What's next?

**Comment by vhmth** [comment]
Likely opening an issue/doing some research in `react-redux`.

**Comment by tshaddix** [comment]
@vhmth Good to hear! Not trying to sell you on one philosophy or another! There are definitely people who argue against the container/presentation component philosophy.

**Comment by vhmth** [comment]
Hahaha check this out: https://github.com/reactjs/react-redux/pull/320

**Comment by tshaddix** [comment]
![186312-well-there-s-your-problem](https://cloud.githubusercontent.com/assets/2173532/17765733/8e66409c-64dc-11e6-9837-f58e712947c4.jpg)

**Comment by vhmth** [comment]
PR opened up against `react-redux`: https://github.com/reactjs/react-redux/pull/465

**Comment by tshaddix** [comment]
@vhmth Thanks for following up on this!

**Comment by vhmth** [comment]
Sure thing! Looks like they're probably gonna accept it. They were asking for me to write some tests so I just squared that away.

**Comment by vhmth** [comment]
@tshaddix my changes have landed in `react-redux`'s beta. We've been testing this beta on our staging extension and will be testing with our beta extension later today. Looks like the next version of `react-redux` will not break with this library. Just thought I'd keep you posted.
