### ISSUE TITLE
Problem with async actions

### ISSUE THREAD

**Issue by danmaz74** [tshaddix/react-chrome-redux#24]
We're testing the tool and after several attempts it looks like the async actions don't work properly.

The best way we found to create a bug report was to publish a very simple example:

https://github.com/ihenvyr/react-chrome-extension

The synchronous action updates the store in the background page, but the asynchronous one doesn't...

**Comment by tshaddix** [comment]
Hi, @danmaz74 !

I glanced over your `aliases` and noticed you're not calling `dispatch()` anywhere inside your [async handler](https://github.com/ihenvyr/react-chrome-extension/blob/master/src/aliases.js#L13). 

Probably need to change this to call `dispatch(originalAction)` on line 13.

**Comment by tshaddix** [comment]
I just messed around with your repository. In your alias, you're returning the original action with the same `type`. This means that you're just going to be calling your alias over and over again. I have  got your example working with just a few tweaks:

```
diff --git a/src/aliases.js b/src/aliases.js
index 007a8c0..19a8ae9 100644
--- a/src/aliases.js
+++ b/src/aliases.js
@@ -1,3 +1,5 @@
+import * as types from './constants';
+
 const addCountAsync = (originalAction) => {
   // works but not async
   // return originalAction;
@@ -6,12 +8,17 @@ const addCountAsync = (originalAction) => {
   return (dispatch, getState) => {
     // return a thunk/promise/etc

-    // simulate server response
-    return setTimeout(() => {
-      console.log('alias addCountAsync', originalAction);
-      // return dispatch(originalAction); // keep on dispatching the action (every 1 second)
-      return originalAction; // no store update
-    }, 1000);
+    return new Promise((resolve) => {
+      // simulate server response
+      return setTimeout(() => {
+        console.log('alias addCountAsync', originalAction);
+        dispatch({
+          type: types.ADD_COUNT_ASYNC_RESOLVED
+        });
+
+        resolve();
+      }, 1000);
+    });
   };
 };

diff --git a/src/constants/index.js b/src/constants/index.js
index 58bd115..465ab95 100644
--- a/src/constants/index.js
+++ b/src/constants/index.js
@@ -1,2 +1,3 @@
 export const ADD_COUNT = 'ADD_COUNT';
 export const ADD_COUNT_ASYNC = 'ADD_COUNT_ASYNC';
+export const ADD_COUNT_ASYNC_RESOLVED = 'ADD_COUNT_ASYNC_RESOLVED';
diff --git a/src/reducers/index.js b/src/reducers/index.js
index c18c333..5366a4d 100644
--- a/src/reducers/index.js
+++ b/src/reducers/index.js
@@ -6,7 +6,7 @@ const count = (state = 0, action) => {
     case types.ADD_COUNT:
       return state + 1;

-    case types.ADD_COUNT_ASYNC:
+    case types.ADD_COUNT_ASYNC_RESOLVED:
       return state + 1;

     default:
```

**Comment by vhmth** [comment]
@tshaddix dope - good find.

@danmaz74 could you explain what might have been confusing to you about using aliases? Aliases are specifically meant to ensure that a certain action happens in the background of your extension. Was something unclear in the documentation? Were you able to find the documentation?

The answers to these questions lead to a better codebase and on-boarding for new people finding this repo.

**Comment by tshaddix** [comment]
@vhmth I think we're going to need to add a better example in under the aliases section. There just isn't enough information out there regarding how to use them in a more complicated scenario. I had a developer email me this a little while ago:

> Hi! I loved your talk about React+Redux with GoGuardian on YouTube. Sad you didn't get the time to talk about async actions with the tool. Could you please make an simple async example out of it? I'm having some trouble making that work with async. I know a custom middleware is needed, but I still can't figure out my problem. I think I and many more would be thankful for a tutorial/example. The examples provided are very good, but none of them have any async action in them

Maybe we can add something to the [examples](https://github.com/tshaddix/react-chrome-redux-examples) repo as well as getting a little more detailed in the wiki?

**Comment by danmaz74** [comment]
First of all, thanks a lot!

Regarding what confused us, I'll wait for my colleague that actually created the implementation to answer (he'll be back on Tuesday).

**Comment by tshaddix** [comment]
@danmaz74 No problem! We look forward to hearing from your colleague

**Comment by vhmth** [comment]
Yep definitely looking forward to it! @tshaddix we could also create free screencasts and embed them into a GitHub page for the repo walking through different use cases of the library. I'd be game to take the lead on that.

**Comment by ihenvyr** [comment]
Hi, thank you for creating this library! I'm the colleague of @danmaz74. What confused me most was implementing the alias. It would be great to add the example usage of async/aliases to the documentation.

Again thank you guys!

**Comment by tshaddix** [comment]
@vhmth It would be great to have some screencasts available! I think we'd all welcome that level of detail.

@ihenvyr No problem! Sounds like something we can definitely help with.

**Comment by vhmth** [comment]
Cool - I go back home to Chicago this weekend and am in a hell sprint for this product launch. On the flight over I'll move the documentation to the main README (I think that's a major cause of confusion) and then see if there's a way to get a GH page going with embedded videos.

**Comment by tshaddix** [comment]
@vhmth Sounds good. Maybe a [GitBook](https://www.gitbook.com/)?
