### ISSUE TITLE
[Question] Could you provide more detail about alias and dispatchResponder

### ISSUE THREAD

**Issue by arthur791004** [tshaddix/react-chrome-redux#26]
Hi,

I originally using redux-thunk for async action, for example:

```
// actions/index.js
function requestData() {
  return (dispatch, getState) => {
    dispatch({
      type: 'REQUEST_DATA',
      ...
    });

    superAgent
      .get(...)
      .end((err, res) => {
        if (err) {
          dispatch({
            type: 'REQUEST_DATA_FAIL',
            ...
          });
        } else {
          dispatch({
            type: 'REQUEST_DATA_SUCCESS',
            ...
          });
        }
      });
}
```

How can I change to use alias & dispatchResponder ?

I think I need to wrap superAgent to an alias action for REQUEST_DATA, but I don't know how to modify my action and how to use reduxPromiseResponder when remote api response..

Thanks.

**Comment by tshaddix** [comment]
@vhmth I know you were planning on working on documentation regarding this. Are you still planning on doing that? If not, I can work on something

**Comment by tshaddix** [comment]
@arthur791004 For now, you can see some working examples with redux thunk here: https://github.com/tshaddix/next-read/tree/master/event/src

**Comment by vhmth** [comment]
https://www.opentest.co/share/aaeb75007b9511e6832debb4fee9069e

**Comment by arthur791004** [comment]
Hi @vhmth,
 
Sorry for asking this question when you are busy. I will see the examples @tshaddix given, and try my best to deal with it. I think I can learn much from that example.

Thanks.

**Comment by vhmth** [comment]
Yo @arthur791004 no problems at all! I've been saying this for a while now - I'm always busy. It is not a pain at all for me to give back to a library that has given so much value to us. I always love giving value. I just have to proactively make time again. Thank *you* for edging this on. :-)

**Comment by vhmth** [comment]
@tshaddix what is your preferred method for hosting/uploading images? I made a quick architecture diagram as an SVG and wanted to include that in the README.

**Comment by tshaddix** [comment]
@vhmth Good question! I use GitHub's cloud by dragging it into a comment or PR, waiting for the link to generate, and then using that link

**Comment by vhmth** [comment]
Gracias

**Comment by vhmth** [comment]
https://github.com/tshaddix/react-chrome-redux/pull/27

**Comment by tshaddix** [comment]
@vhmth Just watched over your video you posted a couple days ago! Congrats on the launch! I'm down to move forward with the readme extensions you outlined.

**Comment by vhmth** [comment]
Thanks man! Another bigger launch coming this week. 😁
