### ISSUE TITLE
[Question] Components not receiving the props

### ISSUE THREAD

**Issue by joshling1919** [tshaddix/react-chrome-redux#28]
Hello!

I'm a former middle school teacher who recently got interested in programming, and I'm currently trying to build a chrome extension, using react-redux, as one of my first projects. I stumbled across react-chrome-redux, and it was exactly what I was looking for!

Unfortunately, I've unable to correctly set it up. I watched the live-code demo and read through all to see what I was missing, but I haven't been able to figure it out. 

I tried to first just replicate the clicker example from the video, so my UI component and background.js basically looks exactly the same as the demo: 

```javascript
import React from 'react';
import {render} from 'react-dom';

import App from './lib/components/app';

import {Store} from 'react-chrome-redux';
import {Provider} from 'react-redux';

const proxyStore = new Store({
  portName: 'example'
});

document.addEventListener('DOMContentLoaded', () => {
  render(
    <Provider store={proxyStore}><App /></Provider>
    , document.getElementById('root'));
});
```

```javascript
import React, {Component} from 'react';
import {connect} from 'react-redux';

class App extends Component {
  constructor(props) {
    super(props);
  }


  componentDidMount() {
    document.addEventListener('click', () => {
      this.props.dispatch({
        type: 'ADD_COUNT'
      });
    });
  }
  
  render() {
    return (
      <div>
        Click Count: {this.props.count}
      </div>
    );
  }
}

const mapStateToProps = (state) => {
  return {
    count: state.count
  };
};

export default connect(mapStateToProps)(App);
```

For some reason, however, the UI component does not seem to actually be receiving the correct props, and when I do click, this error message pops up:

![image](https://cloud.githubusercontent.com/assets/18567829/18822539/d2ef3b54-8365-11e6-9d53-17e192aa238b.png)

This is a portion of my manifest.json:
```json
  "version": "1.0",
  "background": {
     "scripts": [
       "background.js"
     ],
     "persistent": true
   },
  "browser_action": {
   "default_icon": "icon.png",
   "default_popup": "popup.html"
  }
```

Please let me me know if this wasn't the correct place to ask for this type of help, or if any more specific code needed to be provided.

Any help would be greatly appreciated. Thanks so much!

**Comment by vhmth** [comment]
Hey @joshling1919 not sure what the issue could exactly be, but first thing I'd try changing is this:

```
document.addEventListener('DOMContentLoaded', () => {
  render(
    <Provider store={proxyStore}><App /></Provider>
    , document.getElementById('root'));
});
```

to

```
const unsubscribe = poxyStore.subscribe(() => {
  unsubscribe();
  render(
    <Provider store={proxyStore}><App /></Provider>
    , document.getElementById('root'));
});
```

Here's an explanation why: https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage#initializing-ui-components

**Comment by joshling1919** [comment]
Hi @vhmth thanks so much for the prompt response! 

I updated that portion to use the unsubscribe/subscribe pattern, but unfortunately, now nothing is rendering. Previously, with the 'DOMContentLoaded' event listener, it rendered 'Click Count:' but show no numbers, and then it threw an error once I clicked. 

I also inspected background.js and saw that there's an 'Unexpected Import Token' error there, so I'm not sure if it's just a babel/webpack issue:

```javascript
//webpack.config.js
const path = require("path");

module.exports = {
  context: __dirname,
  entry: "./popup.jsx",
  output: {
    path: "./lib",
    publicPath: "/lib/",
    filename: "bundle.js",
    devtoolModuleFilenameTemplate: '[resourcePath]',
    devtoolFallbackModuleFilenameTemplate: '[resourcePath]?[hash]'
  },
  module: {
    loaders: [
      {
        test: [/\.jsx?$/, /\.js?$/],
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'react']
        }
      }
    ]
  },
  devtool: 'source-maps',
  resolve: {
    extensions: ["", ".js", ".jsx" ]
  }
};
```

Thanks again for the help; I really appreciate it.

**Comment by vhmth** [comment]
@joshling1919 would you mind creating a repo showcasing your code? I can take a look.

**Comment by joshling1919** [comment]
@vhmth yeah of course! Thanks.

https://github.com/joshling1919/fantasy-hype-train

**Comment by vhmth** [comment]
@joshling1919 I am looking into this right now, but I noticed you haven't included your command to actually transpile your ES6. If you could include that in a `Makefile` or in your `package.json

**Comment by joshling1919** [comment]
@vhmth That was the issue! Thanks so much for your help.

**Comment by vhmth** [comment]
Sure thing @joshling1919!
