### ISSUE TITLE
Firefox webExt

### ISSUE THREAD

**Issue by julienR2** [tshaddix/react-chrome-redux#29]
Hi ! Still didn't have time to try this, but since Firefox now support WebExtension could this be used as it is in as a firefox extension ?

**Comment by vhmth** [comment]
I'm not familiar with how the Firefox APIs work/layout of their apps, but I'm assuming not. But that makes me wonder how difficult it would be to write an adapter interface that allows you to write FF and Chrome extensions.

**Comment by tshaddix** [comment]
@julienR2 @vhmth Surprisingly, it seems to work out of the box! You can load the [example repo](https://github.com/tshaddix/react-chrome-redux-examples) no problem.

Just be careful the rest of your extension is compatible with the supported APIs:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
