### ISSUE TITLE
Prepare Stable Release 1.0.0

### ISSUE THREAD

**Issue by tshaddix** [tshaddix/react-chrome-redux#31]
I think we're at a point to move towards a "stable" (1.X.Y) release of react-chrome-redux. We are currently "unstable" (0.X.Y) in terms of [SemVer](http://semver.org/). This issue should be used to discuss any remaining public API changes which might be necessary before moving to 1.0.0.

**Comment by tshaddix** [comment]
I think we should get the README to an excellent place. @vhmth Did some great work to make it more readable and navigable. Let's run through it with [these](https://github.com/noffle/art-of-readme) guidelines in mind.

**Comment by vhmth** [comment]
Looked through the README. Honestly, it looks pretty good. Updated a bit though:

https://github.com/tshaddix/react-chrome-redux/pull/32

**Comment by tshaddix** [comment]
Thoughts on moving forward with a 1.0 without #35? I have not fully thought out how to do this feature. I don't think it should be blocking 1.0. Thoughts @vhmth ?

**Comment by vhmth** [comment]
Yeah I think moving to 1.0 without #35 is 100% ok 👌🏾

**Comment by tshaddix** [comment]
@vhmth Cool let's do it! I'll get a PR going
