### ISSUE TITLE
How to pass functions in payload?

### ISSUE THREAD

**Issue by sammkj** [tshaddix/react-chrome-redux#36]
Hello there, I'm trying to pass a function to payload and retrieve it in the middleware. But, it seems like the function that I pass in gets stripped off. I don't see anything in the src that strips functions off the payload. Any ideas how I could solve this? Thanks!

**Comment by vhmth** [comment]
@sammkj in general passing around functions in actions is bad Redux practice. Could you explain your use case?

**Comment by sammkj** [comment]
I'm creating a package that wraps Chrome events and methods in middleware. So, I would just dispatch actions to update store from events and get values from methods. For example, I would dispatch

```
dispatch({
  type: '@@chrome/GET_ALL_COMMANDS',
  get: (commands) => {
    console.log(commands);
  },
});
```

and the middleware would do:

```
if (action.type === '@@chrome/GET_ALL_COMMANDS') {
  const commands = await chrome.promise.commands.getAll();
  action.get(commands);
}
```

I'm new to chrome extension development. So I might be doing something wrong.

**Comment by vhmth** [comment]
Is the purpose of this package to just promise-ify the Chrome commands via actions? Sorry - I still don't understand the purpose of the package.

In this case you're dispatching `@@chrome/GET_ALL_COMMANDS` (assuming that you just want to get the response of that from the background script). If that's the case, this library is supposed to be used in a Redux way. That means that the background wouldn't necessarily return a response, it would update the central Redux store with the list of commands and the content script could get at them.

**Comment by sammkj** [comment]
Nope, `chrome.promise` is provided by [`chrome-promise`](https://github.com/tfoxy/chrome-promise) package.

Maybe I'm overthinking things here. I'm trying to wrap Chrome APIs in redux. So I could just dispatch actions to use the APIs. And that way I don't have to use `chrome.*` directly and my code will be more reusable.

Full snippet here:

```
export default function chromeCommandsMiddleware(): Function {
  return (store: Object): Function => {
    chrome.commands.onCommand.addListener((command: string) => {
      chromeLogger.info(`Receive command: *${command}*`);
    });

    return (next: Function) => async (action: Object): Object => {
      if (action.type === '@@chrome/GET_ALL_COMMANDS') {
        const commands = await chrome.promise.commands.getAll();
        return action.get(commands);
      }

      return next(action);
    }
  };
}
```

If you don't mind I ask, how are you using `chrome.*` in your extension?

**Comment by vhmth** [comment]
Left you a vide @sammkj.

https://www.opentest.co/share/373688f0a85b11e6bb532566e7b8629f

**Comment by sammkj** [comment]
Man, that's the dopest reply I have ever seen on github! Thank you for making the video. I'm gonna checkout opentest.

Based on your video, my understanding is we should use aliases to call `chrome.*`.  And if the API has callback, we should update the store with the callback return value. Is that right? That was what I initially thought about but somehow I decided to do the other way. I guess my issue is solved then!

**Comment by vhmth** [comment]
Yep that's exactly how you should do it! With Redux you should always mutate the store and just let the components update based on the store's value. That way you can always render the same version of your application no matter what. :-)

Very happy you enjoyed the video. Definitely give Opentest a try. Our extension is built with the help of this library, it's super quick, lightweight, and free. :-)
