### ISSUE TITLE
Unable to use with Apollo Client

### ISSUE THREAD

**Issue by sammkj** [tshaddix/react-chrome-redux#37]
Hello there, I tried using this package with Apollo Client but it's not working. Apollo Client was able to fetch results from graphql server but **couldn't dispatch actions to update the store with the fetched result**. I have been investigating this for a few hours now but still couldn't find the problem. Any ideas on what the problem could be? Thanks!

Edit:

I was able to dispatch actions from content scripts. So, by right, Apollo Client should be able to do the same.

**Comment by sammkj** [comment]
This issue is not related to `react-chrome-redux` but 'react-apollo`.

**Comment by tshaddix** [comment]
@sammkj Good to hear you figured it out! Sorry for the late reply!

**Comment by sammkj** [comment]
That's ok! I'm gonna leave a note here for future reference. In order to use Apollo Client with this package, we need to specifically tell Apollo Client to use the store created in `react-redux-chrome`.

For example,  in your `Root` component:

```
class Root extends Component {
  render() {
    const {
      store,  //  this is the store created by `react-chrome-redux`
      client, // normal Apollo client
    } = this.props;
    
    client.setStore(store); // this is a private method in Apollo client. Be sure to always check this.

    return (
      <ApolloProvider store={store} client-{client}>
        <App />
      </ApolloProvider>
    );
  }
}
```

**Comment by tshaddix** [comment]
Great! Thanks @sammkj

**Comment by vhmth** [comment]
Dope thanks for providing a solution @sammkj - super super useful. I updated the code snippet to say `client={client}` instead of `client-{client}` - let me know if that wasn't a typo.

💯

**Comment by sammkj** [comment]
@vhmth oops, definitely a typo! thanks for editing!

**Comment by mironov** [comment]
@sammkj Thank you for the solution!
Am I right that Apollo Client will fetch queries on webpages instead of background page?

**Comment by sammkj** [comment]
@mironov Glad that helped!

Yeap, that's correct if you're using `react-apollo`.
