### ISSUE TITLE
[Question] How to use this with react-router or react-router-redux?

### ISSUE THREAD

**Issue by vanbosse** [tshaddix/react-chrome-redux#39]
Hi,

I've setup an action to login a user after the login form was submitted. I've created a matching alias to have this async action of checking credentials happen in the background page. However, I'm using react-router and would like to "redirect" on a successful login. This happens by doing:

```js
import { browserHistory } from 'react-router';

browserHistory.push('<new-path-here>');
```

As you might expect, having to setup the routing in the popup page (together with the browserHistory) we can't just access the same browserHistory object in the background page. Meaning that one cannot simply redirect a user after a successful login. See code example:

```js
// popup

import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { Store } from 'react-chrome-redux';
import { Router, browserHistory } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';
import getRoutes from './routes';

const store = new Store({
    portName: 'xxx'
});

const unsubscribe = store.subscribe(() => {
    unsubscribe();
    const history = syncHistoryWithStore(browserHistory, store);

    ReactDOM.render(
        <Provider store={store}>
            <Router history={history}>
                {getRoutes(store)}
            </Router>
        </Provider>,
        document.querySelector('#app')
    );
});

```

```js
// background

import firebase from 'firebase';
import { browserHistory } from 'react-router';

// This is an aliased action executing from the background
// with redux-thunk
const loginUser = () => {
    return (dispatch) => {
        firebase.auth().signInWithEmailAndPassword(email, password)
            .then(user => {
                dispatch({
                    type: LOGIN_SUCCESS,
                    payload: user
                });

                // Redirect here
                // This won't work, because the browserHistory obviously differs
                // from the one in the popup page.
                browserHistory.push('/dashboard');
        });
    };
};
```

I hope this is kind of clear? My question however is: is there a way this issue is supported by react-chrome-redux and am I just not seeing it? Or should I use messaging to send a message to my popup page saying: "Hey, all is fine, you can redirect now using the correct browserHistory object"?

Note: don't mind missing imports and such, just assume everything works. I just want to figure out, how I can get back to the browserHistory in a neat way.

Thanks in advance!

**Comment by vanbosse** [comment]
FYI: In the meantime I'm using this workaround:

```js
// popup
const unsubscribe = store.subscribe(() => {
    unsubscribe();
    const history = syncHistoryWithStore(browserHistory, store);

    // @todo: Check if there's a cleaner way to redirect.
    // https://github.com/tshaddix/react-chrome-redux/issues/39
    chrome.runtime.onMessage.addListener(
        function(request) {
            if (request.type == 'redirect') {
                history.push(request.payload);
            }
        }
    );

    ReactDOM.render(
        <Provider store={store}>
            <Router history={history}>
                {getRoutes(store)}
            </Router>
        </Provider>,
        document.querySelector('#app')
    );
});

```

```js
// background

chrome.runtime.sendMessage({
    type: 'redirect',
    payload: '/dist/index.html'
});

````

**Comment by tshaddix** [comment]
Hi @vanbosse, really sorry for the late response. I with family for the holidays but I will try to find some time to jump into this! Thanks for posting the workaround!

**Comment by vhmth** [comment]
@vanbosse I'm not super familiar with `react-router` (yet - we'll be using it extensively in the following months). Just commenting here so I can be subscribed to this thread. :-)

**Comment by tshaddix** [comment]
@vanbosse So looking through this, looks like you've found all the limitations I can think of. 

One suggestion if you don't want to write your own "sendMessage" and handler: Just use a key on the state object to indicate what route the popup should be.

For example, in your alias:

```js
.then(user => {
                dispatch({
                    type: LOGIN_SUCCESS,
                    payload: user
                });

               dispatch({
                 type: POPUP_REDIRECT,
                 payload: 'some-redirect'
               });
        });
```

Then include a corresponding reducer for the `POPUP_REDIRECT` action.

Finally, in your popup you can use:


```js
const lastRoute = // ...

store.subscribe(() => {
    // check store popup router is different than last route
   // redirect if so
});
```

That way you can still manage your routing in your state. This may be a little more manual than you had hoped, but it has the nice property that Redux promotes which is representing your entire app in the stores state.

**Comment by SudoPlz** [comment]
@vanbosse This is very interesting, can you please post your full working code? I mean if you actually used @tshaddix 's suggestion? I'd love to see it, I still haven't understood how to implement this, and react-router is not working with me today..!

**Comment by vanbosse** [comment]
@SudoPlz I didn't use @tshaddix 's suggestion. I continued using the workaround. Since this was code of a test project, it didn't matter all that much.
