### ISSUE TITLE
Why am I having trouble with setting initialState to an object?

### ISSUE THREAD

**Issue by missioeric** [tshaddix/react-chrome-redux#40]
I used this example to setup my extension using react-chrome-redux: https://github.com/tshaddix/react-chrome-redux-examples

Currently in the countReducer, it has:
`const initialState = 0;`

Everything works fine.

But if I update that to 
`const initialState = {
      counter: 0 };`

Then update mapdispatchtoProps from 

`count: state.count`

to 

`count: state.count.counter`

I get an error that says can't find property counter of undefined.

If I setup the initial state as values (not objects), everything works fine.

**What am I not understanding?**

Thanks.

**Comment by vanbosse** [comment]
@missioeric you want to map state instead of actions. Meaning that you should update ```mapStateToProps``` instead of ```mapDispatchToProps```.

**Comment by missioeric** [comment]
@vanbosse 

Thanks so much. Shows you where my mind is.

I am actually updating `mapStateToProps` even though I wrote dispatch above. Sorry about that.

Any other ideas on why making the simple change above in my count reducer:

going from `const initialState = 0;` to `const initialState = { counter: 0 };` 

and then changing in `mapStateToProps` from `count: state.count` to `count: state.count.counter` would return `can't find property counter of undefined`?

**Comment by vhmth** [comment]
@missioeric do you have a minimal example online somewhere I can take a look?

**Comment by missioeric** [comment]
@vhmth Yes, you can see my code here: [https://gist.github.com/missioeric/c5bda70c1dfa4676a73790faa10c4a79](https://gist.github.com/missioeric/c5bda70c1dfa4676a73790faa10c4a79)

Thanks for the help.

**Comment by vhmth** [comment]
@missioeric if that's your root-level reducer, you will need to reference it as `state.counter` - not `state.count.counter`. Right now your store looks like this:

```
{
  counter: 0
}
```

So `state.count` will return `undefined`.

**Comment by missioeric** [comment]
@vhmth Thank you. That did it. I was misunderstanding how the store looked. Thanks for taking the time to look at things for me.

**Comment by vhmth** [comment]
No problem! Glad you got on alright! :)

**Comment by missioeric** [comment]
Actually,

that didn't end up solving things for me.

But, I found this: [https://github.com/tshaddix/react-chrome-redux/issues/5](https://github.com/tshaddix/react-chrome-redux/issues/5)

and realized it was the exact issue I was having.

So, for future readers, **if you find that you can't access nested properties in the state,** use the fix above (also here under Initializing UI Components: [https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage](https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage) )

Thanks for your help @vhmth 

Wouldn't have figured things out without your help along the way.

**Comment by vhmth** [comment]
Hmm @tshaddix this makes me think that we really need to be explicit about this initial connection race condition. Enough people have brought it up that it may warrant an unconventional API (unconventional to redux that is), such as:

```
store.ready(() => {
  // do stuff
});
```

Thoughts @tshaddix? I know you're weary about straying too far from the Redux API, but this is kinda the main race that most people will run into when using the store, and the store isn't just ready to use in the content scripts until it's connected to. I believe this is a good candidate for a more explicit API (which seems necessary due to the nature of the Chrome extension dev environment itself).

**Comment by tshaddix** [comment]
@vhmth I think that's fair! As long as we maintain the existing APIs to be up-to-standards with Redux, additional utility methods are probably just fine. I think this is a good suggestion.

We should also make sure to add something front and center in the README :)
