### ISSUE TITLE
Update README with Sender addition

### ISSUE THREAD

**Issue by tshaddix** [tshaddix/react-chrome-redux#43]
Update the README to include Sender information example merged in #41 . We should also bump the version.

**Comment by vhmth** [comment]
@tshaddix what's your schedule looking like? I probably won't be able to get to this anytime soon (even though it's an easy update). Juggling hiring, coordinating a NYE party, and rebranding our company. :-P

**Comment by durandj** [comment]
I could write up something for the README if it would help and no one has started on it.

**Comment by vhmth** [comment]
That would be awesome @durandj!

**Comment by durandj** [comment]
I have the README done! Do you think you want to have a minor version bump or a patch version bump? I'm thinking a minor since a new feature is being added versus a bug fix.

**Comment by tshaddix** [comment]
@durandj Definitely agree with you. It's a feature addition for sure.

**Comment by vhmth** [comment]
👍

**Comment by tshaddix** [comment]
@vhmth @durandj Alright, we're all clear! GitHub release and NPM publish done. Excellent stuff :) 

We need to get a contributor section on these docs eventually.
