### ISSUE TITLE
Minimal example of communication between background and content scripts

### ISSUE THREAD

**Issue by herodrigues** [tshaddix/react-chrome-redux#45]
Hi @tshaddix , great work!

I was wondering how to use chrome.runtime.sendMessage or similar methods to make scripts communicate between each other.

Or is chrome.local.storage a better solution?

**Comment by vhmth** [comment]
Typically you would want to dispatch an action that fires an alias to ensure that some task happens on the background. The background page would then update the store, which would update your UI in your content/popup scripts.

Take a look at #3 in the README titled:

Optional: Implement actions whose logic only happens in the background script (we call them aliases)

And let me know if that section makes sense. If not, hopefully I can clear it up.

**Comment by herodrigues** [comment]
That's exactly what I want: actions only in background.

I'm.gonna try that.

Thanks

**Comment by vhmth** [comment]
Yep you'll still want to dispatch actions from your UI components (at least as the source propagator), but you can have the logic run in the background via aliases.

**Comment by tshaddix** [comment]
Hey @herodrigues! No doubt it's confusing. I haven't done a good job of documenting the aliases. Thanks @vhmth for pointing in the right direction.

@herodrigues did aliases solve your problem?

**Comment by herodrigues** [comment]
I didn't have time to try that.
Basically what I'm try to do is to inject a sidebar into the page after the user clicks on the extension's icon.

**Comment by tshaddix** [comment]
@herodrigues no worries! That actually shouldn't need to involve `aliases` at all:

In your background page:

```js
// 1. Add a reducer for handling OPEN_SIDEBAR event
const sidebar = (state, action) => {
  if (action.type === OPEN_SIDEBAR) {
    return {sidebarOpen: true};
  } else {
    return state;
  }
}

// 2. Create store with that reducer ...

// 3. On app icon click (I forget the chrome API specs), dispatch directly in your background page
store.dispatch({
  type: 'OPEN_SIDEBAR'
  payload: {}
});
```

Finally, in your content script, you just act based on whether `sidebar.isOpen` is true or false:

```js
// ...

render () {
  // props mapped using react-redux from store
  const {sidebar} = this.props;

 if  (sidebar.isOpen) {
   return (<div>SIDEBAR</div>);
 } else {
   return (<div></div>);
 }

```

**Comment by herodrigues** [comment]
@tshaddix thanks! 

The second part is what I was not understanding very well, but now it's clear.

**Comment by tshaddix** [comment]
@herodrigues Awesome! Let us know if you run into any more problems!

**Comment by herodrigues** [comment]
I'm reopening because I could implement only content to background and not vice-versa.

I still don't understand the need of wrapping the store if there's no chrome.tabs.sendMessage or chrome.tabs.connect in the wrapStore class of react-chrome-redux.

**Comment by tshaddix** [comment]
@herodrigues The `wrapStore` function uses an established port to send state updates back to ui components. You can see it [here](https://github.com/tshaddix/react-chrome-redux/blob/master/src/wrap-store/wrapStore.js#L69)

We're going to need to see some code before we can help you :)

**Comment by herodrigues** [comment]
Thanks again, @tshaddix.

I can't show you the code but good news is that I figured that out :smile: :tada:  

When I have time I'm going to create a minimal example and send a PR here.

**Comment by tshaddix** [comment]
@herodrigues Woohoo! love when that happens :)

**Comment by terry90** [comment]
Remember that the way is to create listeners (eg for chrome.* features) in your background to update your state and make your UI listen to the changes by mapping your props to the state.
Here is a simple example:

`event/src/listener.js`
```javascript
import Config from '../../config/src/config';
import { extractDomain } from './utils/uri';

export function findScope(host) {
  var urls = Config.content_urls;
  var index = Object.keys(urls).indexOf(host);

  if (index != -1)
    return Object.values(urls)[index];
  else
    return null;
}

function setScopeOnTabChanged(scope) {
  return { type: 'SET_SCOPE', scope: scope };
}

export function listenTabChange(store) {
  chrome.tabs.onActivated.addListener(function(infos) {
      var tabId = infos.tabId;
      chrome.tabs.get(tabId, function(tab) {
        // If we are on a supported website, change the scope
        var scope = findScope(extractDomain(tab.url));
        if (scope)
          store.dispatch(setScopeOnTabChanged(scope))
      })
    }
  );
}
```

`content/src/scripts/components/ComponentChooser.jsx`
```jsx
import React, { Component } from 'react';
import {connect} from 'react-redux';
import SomeWebsiteComponent from './someWebsite/Component';
import OtherWebsiteComponent from './otherWebsite/Component';
import { findScope } from '../../utils/scope';
import { SOME_WEBSITE, OTHER_WEBSITE } from '../../../../../config/src/config';
import { setScope } from '../../actions/scope'
import { openNotification } from '../../utils/ui';

class TopMenu extends Component {
  componentWillMount() {
    var scope = findScope(this.props.host);
    if (scope !== this.props.scope)
      this.props.dispatch(setScope(scope));
  }

  componentWillReceiveProps(newProps) {
    var scope = newProps.scope;

    if (scope !== this.props.scope)
      openNotification({description: `Scope now changed to: ${scope}`});
  }

  render() {
    switch (this.props.scope) {
      case SOME_WEBSITE:
        return <SomeWebsiteComponent />;
      case OTHER_WEBSITE:
        return <OtherWebsiteComponent />;
      default:
        return null;
    }
  }
}

function mapStateToProps(state) {
  return {
    scope: state.scope
  };
}

export default connect(mapStateToProps)(ComponentChooser);
```

This is code from my plugin (with irrelevant parts excluded).
It switch UI modules from different folders depending of the website (hostname). Useful for total integrations with many websites.

**Comment by Techdojo** [comment]
@terry90  Apologies if I'm being thick here but I'm trying to follow your example as I also need to trigger some API requests from my background page and notify my store when they complete and I'm sure the answer lies in the `alias` pattern.

Looking at your example above `store` is defined in `index.js` so how can it be called from `listener.js` ???

When I tried a simple example of dispatching a second `store.dispatch()` when the api call returned (I have my api interface separated out into another file) I got a `store is not defined` error message as expected?

Thanks in advance.
8-)

**Comment by vhmth** [comment]
@Techdojo could you link to your example?

**Comment by Techdojo** [comment]
I'll have to try and create an minimal example as a gist - but I think the alias concept is beginning to take shape now.

**Comment by Techdojo** [comment]
@terry90 - I can see that now, I worked through a couple of examples I found online and then re-read the alias example in the getting started and advanced usage sections.

I was eventually able to work it out and the alias middleware has resolved (or should that be reduced :) ) my problem and I can now trigger async events from my UI which get handled correctly in the background.

@tshaddix - this is the first time time I've ever done any extension coding (or react for that matter) and your library has made the process a lot easier - thanks!

**Comment by vhmth** [comment]
@Techdojo love the pun. :-) And I agree! @tshaddix made it possible for us to create our extension too. Our extension code was garbage without `react-chrome-redux`. Huge ups to Tyler.

**Comment by tshaddix** [comment]
@Techdojo @vhmth You guys give me too much credit. I just work here :)

The package has become useful because of all the awesome contributions from everyone else :)

**Comment by herodrigues** [comment]
Guys, I gave up using @tshaddix's library and I've done an example using Flux.
I had a problem using Redux because I was using another library that does not support Redux.

In the end, it's based on react-chrome-redux structure. I wrote a post about that
http://herodrigues.me/javascript/2017/03/15/small-chrome-extension-react-flux/

**Comment by vhmth** [comment]
Woah! Glad you were able to generalize something to work with Flux. Great work. :-)

**Comment by tshaddix** [comment]
@herodrigues Awesome stuff! Good work!
