### ISSUE TITLE
State is undefined 

### ISSUE THREAD

**Issue by onurhb** [tshaddix/react-chrome-redux#52]
I have a simple reducer as following:

```
import * as ActionTypes from '../../shared/ActionTypes'

const initialState = {
  authorized : 0
}

export default (state = initialState, action) => {
  switch (action.type) {
    case ActionTypes.LOGIN:
      return {
        authorized : 1
      }
    case ActionTypes.LOGOUT:
      return  {
        authorized : 0
      }
    default:
      return state;
  }
};
```

When I try to access authorized from my popup, it throws an error: authorized is undefined. However, if I changed the initial state to `const initialState = 0`, it works. 

This does not simply work: `<h1>{this.props.auth.authorized}</h1>`.
If I remove this line and try to print this.props.auth.authorized inside render(), I see that it is undefined first, then 0.
I guess the state is not initialized properly?

Full code : https://github.com/onurhb/Test

**Comment by tshaddix** [comment]
Hi @onurhb !

There is a slight race condition at the beginning of a store setup due to how chrome ports work. Let me know if this is helpful to you: https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage#initializing-ui-components

**Comment by onurhb** [comment]
Thanks! That works perfectly. 🥇

**Comment by tshaddix** [comment]
@onurhb Glad to hear it!

**Comment by yegor211** [comment]
Hey @tshaddix 

Hope you can take a quick look. I experience an issue where the state is ready after .ready() promise and then gets wiped to initial values right after. I couldn’t track down anything extra helpful, but there are some things that may help:
1) debugged port messages - package sends two messages for initialisation (type: chromex.state or something like that, not a patch) - and second one has “initial state values”
2) this is the most prominent hint - it happens only within a certain flow - if I open options page -> open  side panel - side panel will be affected. And the opposite way the same, but options page will be affected. This is extra weird.

It also sometimes doesn’t fail, but quite rarely. If I manually attempt to reload the options page/side panel eventually it will get proper state. No issues when they act independently and if the options page is not active (but open) - side panel will fail much less, but still will sometimes.

**Comment by yegor211** [comment]
It will also act like that not with an options page but any extension page that also creates proxy store. This drives me crazy tbh
