### ISSUE TITLE
Is _sender set when action comes from Devtools panel?

### ISSUE THREAD

**Issue by missioeric** [tshaddix/react-chrome-redux#53]
I'm using react-chrome-redux to develop a devtools panel extension. It appears that the _sender is not set on actions that are sent from this panel.

Have I missed something?

**Comment by vhmth** [comment]
My guess is that `sender` does not exist when messages are sent from that context. @missioeric could you set a breakpoint in `wrapStore` here and see if that's the case?

https://github.com/durandj/react-chrome-redux/commit/d188a78f45a2023b8cd1e708aa9c003e6f700ffa

**Comment by vhmth** [comment]
cc @durandj in case he has some off-the-head reasoning.

**Comment by zalmoxisus** [comment]
Note that Redux DevTools Extension, by default, serialize data via `JSON.stringify`, which could omit some special data, like `JSON.stringify({ f: function smth(){/* ... */ }) === '{}'`. To enable support for special data, set [set `options` of `serialize` parameter to `true`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#symbols-or-other-unserializable-data-not-shown). More details [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md).

**Comment by tshaddix** [comment]
Good call @vhmth. @missioeric ,  @durandj just added the `sender` property straight from [runtime.onMessage](https://developer.chrome.com/extensions/runtime#event-onMessage). Can you confirm that a sender property is expected from messages from devtool panels?

**Comment by missioeric** [comment]
@tshaddix After researching it does not appear that a sender property is expected from messages from devtool panels. Sorry about that!

[https://developer.chrome.com/extensions/devtools](https://developer.chrome.com/extensions/devtools)

**Comment by tshaddix** [comment]
@missioeric No problem! :)
