### ISSUE TITLE
Support for WebExtensions?

### ISSUE THREAD

**Issue by AgrimPrasad** [tshaddix/react-chrome-redux#54]
Browsers seem to be standardizing their extensions API with [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)

Does react-chrome-redux work with WebExtensions out of the box or will some modifications have to be made for this to work?

**Comment by vhmth** [comment]
cc @paulius005

@tshaddix have you done any research here? I know someone else brought this up before. I think the Loom team was thinking about testing this out at some point (no definitive date), but we'd be happy to contribute back if we're able to get it to work. Our goal is to get Loom to work in FF and IE Edge if possible.

**Comment by paulius005** [comment]
+1 to @vhmth

**Comment by tshaddix** [comment]
@AgrimPrasad @paulius005 last time I checked (#29) Web Extensions work out of the box! Let us know if you find otherwise.

**Comment by tshaddix** [comment]
@vhmth Yes sir! We had someone ask about this a little while ago.

The only change that would have caused problems in this compatibility is the extension change in #49. That said, it looks like it's the exact same API (which is expected): https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage

**Comment by vhmth** [comment]
Ah I see. That should be easy to shim. I'll keep this open until we have it working then. Thanks for that little bit of info @tshaddix.

**Comment by AgrimPrasad** [comment]
@tshaddix Great to hear that. I'll try it out in my project and raise any issues if found.

**Comment by tshaddix** [comment]
@vhmth no problem!

@AgrimPrasad sounds good! Let's reopen this if you do.

**Comment by AgrimPrasad** [comment]
@vhmth @tshaddix I found that this library doesn't work in Firefox anymore due to the use of chrome.runtime.onMessageExternal which is not supported by Firefox yet as per https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#runtime

Seems to have been broken by this commit made around a month ago: https://github.com/tshaddix/react-chrome-redux/commit/196934b2146390db1056df384e7357e191a90812

Please re-open this issue for tracking, thanks.

**Comment by tshaddix** [comment]
@AgrimPrasad Got it! Thanks for checking back in.

**Comment by tshaddix** [comment]
@AgrimPrasad Looks like a simple conditional check solves the issue. I'm going to wait for @vhmth to double check me before I merge and publish.

**Comment by vhmth** [comment]
Commented, but overall great, simple fix @tshaddix

**Comment by AgrimPrasad** [comment]
@tshaddix Thanks for the quick and elegant fix!

**Comment by tshaddix** [comment]
This has been released in v1.3.1. Thanks @AgrimPrasad for following up on this and @vhmth for the review!

**Comment by AgrimPrasad** [comment]
Thanks for the quick work @tshaddix and @vhmth 

Unfortunately, it seems like there's still some issue when testing with my extension (https://github.com/AgrimPrasad/mozilla-observatory-extensions) in Firefox. The extension loads correctly initially, but it seems like aliases aren't being dispatched correctly with the following error message logged in the console:

```
resp is undefined  bundle.js:52809
	dispatch/</< moz-extension://6b705b44-8c27-434e-be2b-0f564d4718a7/bundle.js:52809:15
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:60:14
	runSafeWithoutClone resource://gre/modules/ExtensionUtils.jsm:255:38
	bound runSafeWithoutClone self-hosted
	wrapPromise/< resource://gre/modules/ExtensionUtils.jsm:428:13
	onFulfilled self-hosted
	onFulfilled self-hosted
```

From the brief amount of time I've spent to try and debug this issue, it seems that `extensionId` is `undefined` in the dispatch function... I'll have to debug it further but probably will only have time later to do so.

Note that react-chrome-redux-examples load fine, with actions being dispatched. Therefore, I believe this should be an alias related issue.

@tshaddix Should we create a separate issue for this?

**Comment by tshaddix** [comment]
@AgrimPrasad Bummer deal! Yea can we make an issue to track this specific bug?

**Comment by vhmth** [comment]
I think this will be fixed with https://github.com/tshaddix/react-chrome-redux/issues/65 if you're cool with waiting for that @AgrimPrasad. Otherwise, let's not close this and address. :-)

**Comment by AgrimPrasad** [comment]
Ya, I think we should properly resolve all outstanding web extensions issues (including this one)  with #65 as I don't know if this will be the last issue encountered by me...
