### ISSUE TITLE
Make dispatch and getState available in alias

### ISSUE THREAD

**Issue by EdmundLeex** [tshaddix/react-chrome-redux#58]
I might be using a bad practice, but I feel like there is a need for making `dispatch` and `getState` available in `alias`. 

Reason being if I want to make remote API calls in the background page, and then dispatch an action when the response comes back, it seems I would be out of luck. I am thinking of using `alias` being kind of like using a `thunk`, where I can have an impure function that also dispatches other actions, and have access to the state.

I see that the `store` is already available in the closure. Any reason you didn't make that available?

**Comment by vhmth** [comment]
Edmund you can use `redux-thunk` with your background store and then in your alias function just return what `thunk` expects (a function with the signature `(dispatch, getState) => { ... }`.

**Comment by AgrimPrasad** [comment]
@EdmundLeex You can refer to my previous comments about aliases and thunks in issue #46 . 

You can also refer to https://github.com/AgrimPrasad/mozilla-observatory-extensions/blob/master/src/aliases/aliases.js for an in-progress example of how to use thunks with aliases.

**Comment by EdmundLeex** [comment]
@vhmth @AgrimPrasad Thanks guys! Moment of enlightenment :D
