### ISSUE TITLE
aliases middleware need to be first?

### ISSUE THREAD

**Issue by DeDuckProject** [tshaddix/react-chrome-redux#59]
We've tried to implement this part of the docs (advances usage)
```javascript
import {alias} from 'react-chrome-redux';

import aliases from '../aliases';

const middleware = [
  alias(aliases),
  // whatever middleware you want (like redux-thunk)
];

// createStoreWithMiddleware... you know the drill
```

We've had some trouble with our promise-middleware not firing after using the aliases, and we've found out that the aliases middleware needs to be the first in the middleware chain.
I think this needs to be more clear in the docs.

Do you guys agree?

**Comment by tshaddix** [comment]
@DeDuckProject Makes sense to me!

**Comment by vhmth** [comment]
Hmm great catch. I probably didn't catch this since the `alias` middleware was just applied first from the example, but explicitness is good! 👍

**Comment by vhmth** [comment]
@DeDuckProject would you mind opening a PR that updates the docs? If not, I'll get to it later tonight. :-)

**Comment by DeDuckProject** [comment]
Will do 👍👍

**Comment by DeDuckProject** [comment]
Oops, I see the there isn't a way to PR the wiki... so probably the owner is the only person that can do it?
@vhmth

**Comment by tshaddix** [comment]
@DeDuckProject I opened up the wiki permissions 👍

**Comment by DeDuckProject** [comment]
@tshaddix Thanks, done.
```javascript
import {alias} from 'react-chrome-redux';

import aliases from '../aliases';

const middleware = [
  alias(aliases),  // this should always be the first middleware
  // whatever middleware you want (like redux-thunk)
];

// createStoreWithMiddleware... you know the drill
```

**Comment by vhmth** [comment]
Woops not sure why I asked for a PR. So used to README updates. Gracias @DeDuckProject!

**Comment by Nishchit14** [comment]
I can not see this updated doc. Where is it?

**Comment by DeDuckProject** [comment]
@Nishchit14 https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage
