### ISSUE TITLE
Consider dropping "React" from package name

### ISSUE THREAD

**Issue by tshaddix** [tshaddix/react-chrome-redux#63]
This package originally included `react` in the package name because it provided utilities for working with react components.

That was very short lived and this package no longer has anything to do with `react`. This was brought up in #11 .

It would be pretty straight-forward to drop `react` from the package name:
- Publish current code under npm package `chrome-redux`
- Rename github repo to `chrome-redux`
- Add deprecation message to `react-chrome-redux` npm package pointing at `chrome-redux` for any version over `1.3.1`

What do you think @vhmth ?

**Comment by vhmth** [comment]
Let's do it. How serious are we considering supporting other extension environments? Another one could be `extension-redux` or `web-extension-redux`. I'm cool with going with `chrome-redux` for now though while we figure out that story over time.

**Comment by tshaddix** [comment]
@vhmth I'm fairly serious about it. I'd love to support as many as possible as long as they can all agree on an API (either through polyfills or direct support). 

We definitely could opt for something with web extensions in the future. I looked around for any other packages in this namespace and found one that seems to have been very "inspired" by the diagrams you did the for README: https://github.com/ivantsov/redux-webext :P

**Comment by vhmth** [comment]
LOL "inspired". 😆

Cool man I'm all for renaming this to `chrome-redux` for now though.

**Comment by tshaddix** [comment]
Perfect. PR included.

**Comment by tshaddix** [comment]
Let's reconsider this after #65
