### ISSUE TITLE
Empty state object passed on first call

### ISSUE THREAD

**Issue by Techdojo** [tshaddix/react-chrome-redux#67]
Not sure if this is an issue, a gotcha, the fact that I'm using the library wrongly or just the way react works (still new to this) - but I've noticed that when sending state from my event page to either the popup or content script that on the first call to mapStateToProps() that the state object is empty so my initial render function often get's "can't access ... of undefined" errors.

I got round the issue by having mapStateToProps return suitable defaults if the expected fields were missing.

Just thought I'd mention it.

AND...

Then I found the same point mentioned in the closed issues (#52) - https://github.com/tshaddix/react-chrome-redux/issues/52 and the fix mentioned there also worked for me.

Feel free to close this issue if needs be :)

**Comment by tshaddix** [comment]
Glad you could find the solution with limited effort!

Yes, there is a bit of a race condition when the content script initializes and when the first state is sent down to it. The solution mentioned in #52 is the best way to counter it :)

**Comment by vhmth** [comment]
@Techdojo if you notice in the [first code snippet](https://github.com/tshaddix/react-chrome-redux#1-add-the-proxy-store-to-a-ui-component-such-as-a-popup) of the README, there is a `store.ready` function on the content script store. This store can return or a promise or take a callback:

```
store.ready().then(() => {
  // connected to background now
});
```

OR

```
store.ready(() => {
  // connected to background now
});
```

**Comment by tshaddix** [comment]
@vhmth Whoops forgot to mention that. Thanks!
