### ISSUE TITLE
Store per content script/tab, synchronized with browserAction

### ISSUE THREAD

**Issue by collinsauve** [tshaddix/react-chrome-redux#68]
First off, let me say I love this library.  I am already using it to synchronize a store globally between all tabs and it works great!

However I have some data that is in a per-tab context, that needs to be accessible to the browserAction.  I currently have some rudimentary message passing using callbacks where the browserAction does something like the following to "request" the state: 

(note that I'm using Mozilla's [webextension-polyfill](https://github.com/mozilla/webextension-polyfill), hence the promise-based `browser` functions)

```
async function requestData() {
    const tabQuery = {
        active: true,
        currentWindow: true
    };
    const tabs = await browser.tabs.query(tabQuery);

    const message = {
        verb: 'tabData_get',
        body: { }
    };
    const response = await browser.tabs.sendMessage(tabs[0].id, message)
    await this.receiveTabData(body);
}
```

The content script then responds directly to that message with the data. 

I would love to be able to use the same pattern with a synchronized Redux store here.  Obviously I don't expect anyone to write this for me, but was hoping for some insight as to whether or not you think this *could* work, and if I got it working I could submit a PR.

Here's my general thinking for a solution:

* The wrapped store would live in the content script
* The proxy store would live in the browserAction script
* The background page would forward `chromex.dispatch` to the tab, and `chromex.state` to the browserAction
* Since tabs and their stores are ephemeral, I need to avoid storing a copy of the tab state in the background script.

**Comment by collinsauve** [comment]
Sorry to complicate things further but let me also add another thought I've had:

I have a different content script that injects an iframe into the DOM and synchronizes some data with that via regular (non-extension) message passing.   I'm really looking to generalize this approach to allow me to have stores and proxy stores in any context.

**Comment by tshaddix** [comment]
Glad to hear this has been useful for you!

That's definitely an interesting problem. One solution that some of us have used in the past is to store the per-tab information under a key for each tab id in your store using the sender information passed with a background action (added in #41).

Then you can use a simple utility like this to let a content script discover it's tab id:

[on event page](https://github.com/tshaddix/next-read/blob/master/event/src/lib/tab-identifier/index.js)
[on content script](https://github.com/tshaddix/next-read/blob/master/content-script/src/scripts/lib/tab-identifier-client/index.js)

That only seems to solve the first part of your problem, however...

**Comment by collinsauve** [comment]
Thanks for the suggestion @tshaddix.  Would that mean that all tab data is stored in the background page, and closed tabs' data would hang around forever?

**Comment by tshaddix** [comment]
@collinsauve I personally listen for the `onRemove` event on the tabs namespace and fire off a `CLEAN_TAB_DATA` that informs tab-specific reducers to remove that tab's data. Not saying it's the best way, but it definitely "works" :)

**Comment by vhmth** [comment]
@collinsauve we do this for our Gmail integration on the [Loom extension](https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb).

Basically, we store a state where we have a mapping from tabID -> state of the gmail integration for that tab. As @tshaddix mentioned, we listen for `onRemove` on the tabs object to clear the state for a tabID if it's closed.

Another thing to note is that aliases receive `_sender` property which include the tab info:

```
const aliasHandler = ({ _sender }) => {
  // I can access _sender.tab.id now to know who dispatched this action to me
};
```

You don't need to do anything to get this to work. It works [automagically](https://github.com/tshaddix/react-chrome-redux#4-optional-retrieve-information-about-the-initiator-of-the-action).

**Comment by collinsauve** [comment]
Thanks for the suggestions guys, I may end up using that for the per-tab part.

FYI For the second part I mentioned above (syncing between content script and a frame): I started a rewrite of this library which attempts to decouple and inject the chosen message passing implementation into the rest of it.   Its a pretty heavy change.  I also hate the interface and will probably change it.  You can find it [here](https://github.com/collinsauve/react-chrome-redux) if you're curious.

I actually did get it working very late last night using regular `window.addEventListener('message', callback);` and `targetWindow.postMessage(message, "*")` 

Example usage:

```
// content.js

// Receives dispatch messages on window.addEventListener('message', ...)
// Sends store updates over frame.contentWindow.postMessage

import { createStore } from 'redux';
import { wrapStore, messagePassing.* } from 'react-chrome-redux';

const store = createStore(...); // a normal Redux store
const frame = ...; // find your iframe in the DOM

wrapStore(store, {
  dispatchListener: new messagePassing.WindowMessageListener(),
  storeSubscription: new messagePassing.WindowPostMessageStoreSubscription({targetWindow: frame.contentWindow})
});
```

```
// frame.js

// Receives state updates over window.addEventListener('message', ...)
// Sends dispatch messages over parent.postMessage

import { Store, messagePassing.* } from 'react-chrome-redux';

const store = new Store({
  stateListener: new messagePassing.WindowMessageListener({targetWindow: parent});
  dispatchSender: new messagePassing.ParentPostMessageSender();
});
```

Anyways... I'm going to close this issue for now.  I may open a PR under another title (ie "allow configuration of message passing") if I make more progress.

**Comment by vhmth** [comment]
@collinsauve where is your frame being loaded from? If you control the code in your frame, you can also have that frame load a script that connects to the background store using this library. That's what we do for our camera bubble in Loom. We actually have multiple content scripts that connect to the background script from both iframes and ShadowDOM elements.

**Comment by collinsauve** [comment]
@vhmth the frame is a `chrome-extension://` url.  I didn't know I could connect to the background store this way.  I will do that, TYVM again for the help!

**Comment by vhmth** [comment]
@collinsauve for sure it's almost kinda magical :-) Anything from your `chrome-extension://` URL can connect.

**Comment by omerdn1** [comment]
@vhmth can you elaborate on how you implemented the script that connect an iframe with the background store?
