### ISSUE TITLE
promiseResponder payload clarification

### ISSUE THREAD

**Issue by CrustyJew** [tshaddix/react-chrome-redux#69]
I edited the wiki page under 'Advanced Usage' to clarify that the payload of the returned object is the data that actually gets resolved by the promiseResponder in the content script. 

Not sure if I stated it in the clearest way etc so it might need further clarification, but it wasn't very clear to me why returning just the object I wanted wasn't resolving the promise correctly (it was coming back as undefined)

**Comment by vhmth** [comment]
@CrustyJew could you link to the exact wiki page here for posterity? Where are you returning an object? Are you returning in an action creator or an alias?

**Comment by CrustyJew** [comment]
[Here is the exact revision](https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage/68cfe7984dd1b295fb49eed4540b87abb99436a5).

I was using an alias in my background page. Returning `{url:'some url'}` didn't work, but returning `{type:'Dummy_action', payload: url}` resolved to the `url`

**Comment by vhmth** [comment]
Ah I see. Very strange - that actually explains some odd behavior I've seen in the past. @paulius005 and I always make sure to return promises in our aliases, but @tshaddix maybe we can automatically wrap the value of a return in aliases in a promise so the promiseResponder can handle it?

**Comment by tshaddix** [comment]
From what I understand (and [see](https://github.com/tshaddix/react-chrome-redux/blob/master/src/wrap-store/wrapStore.js#L17)), the `promiseResponder` wraps values in `Promise.resolve` regardless of if they are a promise or not. 

This seems to be related to the fact that an alias should return a valid action.
