### ISSUE TITLE
Cannot run tests 

### ISSUE THREAD

**Issue by collinsauve** [tshaddix/react-chrome-redux#74]
I am getting this error when running the tests: (full output is [here](https://gist.github.com/collinsauve/fd2675b866bb008ed2c47e23cdf478df).)

> '.' is not recognized as an internal or external command,
> operable program or batch file.

On commit f2eb46f80f35a4022174f8ce569cfedb4f6ed92e
Node: v7.3.0
npm: v3.10.10
OS: Windows 10 v1607 Build 14393.447
Running in MINGW32
Bash version:  4.3.46(2)-release (x86_64-pc-msys)

**Comment by collinsauve** [comment]
Note that this just started recently (I suspect the addition of linting).  I was able to run the tests earlier this week.

**Comment by paulius005** [comment]
@collinsauve ah... looks like a backward vs forward slash problem with Windows

**Comment by collinsauve** [comment]
To clarify: I am using bash on Windows, which is supposed to use forward-slashes and unix-style paths... (ie `C:\Windows\System32` is located at `/c/Windows/System32`)

Most things do work, and I have used linters in other projects (I can compare versions in a moment)

Any specific suggestions?

**Comment by paulius005** [comment]
are you able to run `npm run-script lint` by itself?

if you switch the `lint` script in `package.json` to 

`"lint": "node_modules/.bin/eslint src/**/*.js && node_modules/.bin/eslint test/**/*.js",`

does it help?

**Comment by collinsauve** [comment]
I get the same error with `npm run-script lint`.  
I get this error with I make the change you suggested:
> 'node_modules' is not recognized as an internal or external command,
> operable program or batch file.

I *can* run this command by itself from bash, which allows me to actually do the linting:

```
./node_modules/.bin/eslint src/**/*.js && ./node_modules/.bin/eslint test/**/*.js
```

I think its something to do with the `&&`?

**Comment by collinsauve** [comment]
My guess this is a problem with npm on Windows.   Will keep looking along those lines.  Thanks for your help so far - please don't feel like you need to do any more digging yourself.

**Comment by collinsauve** [comment]
Yup, definitely a problem with the chaining of commands in npm.

This change to `package.json` works: https://github.com/collinsauve/react-chrome-redux/commit/9beafac62917016a9721107edb4d0ea3b01d1f2d

If you want to make such a change, you can use that.
If you don't care about Windows, I wouldn't blame you for just ignoring this.  I'll try to beg npm maintainers to fix this.

**Comment by vhmth** [comment]
Totally cool with this change for making Windows work. :-)

We're dealing with web stuff - all OS's should be supported! Mind opening a PR? I can approve it quick and you could rebase your other PR off it. Really appreciate the help here @collinsauve

**Comment by paulius005** [comment]
@collinsauve oh sweet! Glad you worked through it. I learned something today :)

**Comment by collinsauve** [comment]
Closed PR #75, PR #76 is better.

[This issue on npm about this](https://github.com/npm/npm/issues/4040) was closed with a [comment](https://github.com/npm/npm/issues/4040#issuecomment-27159695) that says:

> Also, never ever write ./node_modules/.bin/ in your scripts.

**Comment by collinsauve** [comment]
@tshaddix I got hit by this again today, so I was hoping see if we could resolve this soon (and then I don't have to keep stashing/popping my fix for this)

There are right now 2 different ways of fixing this:
* PR #76 - changes how babel and eslint are invoked.  As @vhmth argues there, this can be non-deterministic.
* PR #83 - splits the npm tasks apart in order to work around the issue on Windows.  

I apologize for all the confusion on this!

**Comment by tshaddix** [comment]
Hi @collinsauve. Sorry it's been awhile since I've jumped into the convo. Thanks @vhmth for taking this on. I just caught up on the whole conversation. There were bits and pieces scattered around this project.

#83 is very simple and straight forward. It's really just segmenting the tasks which is totally fine with me. I do have the same question as @vhmth which is referenced above in #83 in that I don't understand how it fixes the race condition. That said --- I have not used Windows as a dev environment for a couple years so my knowledge of it is fairly limited now-a-days.

If you can confirm that #83 does fix this then I don't see any reason we shouldn't move forward with that solution.

**Comment by tshaddix** [comment]
@collinsauve Oh, also, thanks for being a contributor :)

**Comment by collinsauve** [comment]
You're very welcome, love the project - it really simplified a lot of the synchronization code in the extension I work on at my day job... so happy to help!

**Comment by vhmth** [comment]
@collinsauve commented on your PR
