### ISSUE TITLE
Persistent background pages deprecated

### ISSUE THREAD

**Issue by sporkd** [tshaddix/react-chrome-redux#8]
Love the concept, but I was reading in the Chrome extension docs that persistent background pages are deprecated in favor of event pages (`"persistent": false`). Under [Best practices when using event pages](https://developer.chrome.com/extensions/event_pages#best-practices) it says:

> 3. If you need to keep runtime state in memory throughout a browser session, use the storage API or IndexedDB. Since the event page does not stay loaded for long, you can no longer rely on global variables for runtime state.

Just wondering what your thoughts are since I believe react-chrome-redux keeps the state in background. Would you still recommend using react-chrome-redux on a new project right now? Or do you think it would be somewhat easy (or even possible) to change it to a non-persistent event page that kept state in local storage?

**Comment by tshaddix** [comment]
@sporkd Totally! I actually use it with an event page in a little side project. Basically, you just listen for changes on the redux store and tie something to persist it to localStorage (or whatever else you want):

https://github.com/tshaddix/next-read/blob/master/event/src/setup.js#L30-L46

Then you can load it up when the event page reactivates:

https://github.com/tshaddix/next-read/blob/master/event/src/index.js#L11-L20

Thoughts?

**Comment by sporkd** [comment]
Oh awesome! Thanks for sharing that example.  I'll check it out and let you know if I have any additional thoughts.

**Comment by tshaddix** [comment]
Sounds good! Closing for now but feel free to continue the convo!

**Comment by 3flex** [comment]
@tshaddix looks like the next-read example is no longer on github. Can you point towards another example that doesn't rely on persistent background pages? I could probably figure it out but examples always help :)

Thanks!

**Comment by tshaddix** [comment]
@3flex Sorry about that! Don't remember why I took it public. It should be open now!

[Here is the code](https://github.com/tshaddix/next-read/blob/master/event/src/index.js#L31-L58) in that project that persists the background store. @sriharrsha This should help you as well.

**Comment by petemill** [comment]
@tshaddix That repo is no longer visible, the permalink doesn't even work. Do you have a working example?

**Comment by tshaddix** [comment]
@petemill I have the original example code here:

```js
// @flow

/* global chrome */

import {wrapStore} from 'react-chrome-redux';
import throttle from 'lodash/throttle';
import omit from 'lodash/omit';

import {
  PORT_NAME,
  TAB_ID_TYPE
} from '../../shared/constants';
import {
  rebuildBookmarksAndFolders
} from './actions/bookmarkTree';
import {
  removeTabMeta,
  handleTabChange
} from './actions/tab';

// TEST CODE
import {
  selectFolder
} from './actions/selectedFolders';
// END TEST CODE

import Store from './store';

let store = null;

chrome.storage.local.get([
  'state'
], ({state}) => {
  store = Store(state || {});

  wrapStore(store, {portName: PORT_NAME});

  /**
   * Save the current store state to local storage
   */
  const saveState = () => {
    if (!store) {
      return;
    }

    console.info('Saving state to chrome.storage.local');

    const state = store.getState();

    chrome.storage.local.set({
      // remove bookmark folders from taking up unnecessary space
      state: omit(state, 'entities')
    });
  };

  // On new state, persist to local storage
  const throttledSave = throttle(saveState, 10000, {trailing: true, leading: true});
  store.subscribe(throttledSave);

  // Initialize the store entities
  store.dispatch(
    rebuildBookmarksAndFolders()
  );

  // TEST CODE
  store.dispatch(
    selectFolder({
      folderId: '87',
      foldterType: 'silly'
    })
  );

  store.dispatch(
    selectFolder({
      folderId: '88',
      folderType: 'smart'
    })
  );
  // END TEST CODE
});

// Bookmarks

/**
 * Listener for any changes
 * to the bookmark tree
 * which would require updates
 * to store state
 */
function onBookmarkTreeChange () {
  if (!store) {
    return;
  }

  store.dispatch(
    rebuildBookmarksAndFolders()
  );
}

chrome.bookmarks.onMoved.addListener(onBookmarkTreeChange);
chrome.bookmarks.onChanged.addListener(onBookmarkTreeChange);
chrome.bookmarks.onCreated.addListener(onBookmarkTreeChange);
chrome.bookmarks.onRemoved.addListener(onBookmarkTreeChange);

// Tabs

/**
 * Fired when a tab is updated
 * @param id The id of the updated tab
 * @param changes
 * @param tab
 */
function onTabUpdated (id, changes, tab) {
  if (!store) {
    return;
  }

  store.dispatch(
    handleTabChange(id, tab.url)
  );
}

/**
 * Fired when a tab is created
 * @param id The id of the tab
 * @param url The url of the tab
 */
function onTabCreated ({id, url}) {
  if (!store) {
    return;
  }

  store.dispatch(
    handleTabChange(id, url)
  );
}

/**
 * Fired when a tab is removed
 * @private
 */
function onTabRemoved (tabId) {
  if (!store) {
    return;
  }

  store.dispatch(
    removeTabMeta(tabId)
  );
}

chrome.tabs.onCreated.addListener(onTabCreated);
chrome.tabs.onUpdated.addListener(onTabUpdated);
chrome.tabs.onRemoved.addListener(onTabRemoved);

// Tab ID Client

/**
 * Called when receiving a new message
 * @param message
 * @param tab
 * @param sendResponse
 */
function onMessage (message, {tab}, sendResponse) {
  if (message.type === TAB_ID_TYPE) {
    sendResponse({tabId: tab && tab.id});
  }

  return false;
}

chrome.runtime.onMessage.addListener(onMessage);

// On extension install
// chrome.runtime.onInstalled.addListener(details => {
//   if (details.reason === 'install') {
//     // get the welcome page path
//     const welcomePageUrl = chrome.extension.getURL('welcome.html');
//
//     chrome.tabs.create({url: welcomePageUrl}, () => {});
//   }
// });
```
