### ISSUE TITLE
Advice on integrating react components into content scripts

### ISSUE THREAD

**Issue by Techdojo** [tshaddix/react-chrome-redux#80]
Hi folks,
I'm having a blast with this library and progress on my extension is progressing well - having a background store and a fully react powered popup window is awesome, however I'm running into a bit of a brick wall when it comes to the content injection side.

In Tyler's original ReactChromeRedux example he's creating a single anchor div at the top of the page and then injecting his react component into that div and that's all.  One of the primary uses of my extension is to augment a page of Google search results adding a prefix to results matching a specific criteria - in this instance is the correct pattern to effectively replicate the above pattern for each result therefore having multiple calls to the render method each one rendering it's own `<provider>` instance eg.
```
for(i=0;i<injectIDList.length;i++) {
   render(
      <Provider store={proxyStore}>
         <App/>
      </Provider>
  , document.getElementById(injectIDList[index]);
}
```
Or is there a better pattern I should be using (or maybe even dropping back to vanilla JS).

Any advice would be gratefully received.

Jon...

**Comment by Techdojo** [comment]
After a period of hacking about - I can confirm that the above pattern actually works reasonably well.

The thing (for any people just getting started with this) to remember is that your `content/index.js` file is (re)run every time a new page (that matches the pattern specified in the `"content_scripts"` section of your manifest) is accessed.

Ideally wrap the JS code in an IIFE but you can also run it directly then scan your page looking for the various insertion points - then for each insertion point ideally create a `<div>` with a unique `id` reference at that point and then make a call to `render` as above with the required component wrapped in a `<Provider>` that way the component will have access to the background store.

Here is a cutdown example of my `content/index.js` page for reference.

```
//----------------------------------
// This is the code that is run every time a matching is opened when the extension is active...
//----------------------------------
import React from 'react';
import {render} from 'react-dom';
import {Provider} from 'react-redux';
import {Store} from 'react-chrome-redux';
import MyComponent from './components/MyComponent/MyComponent';
const proxyStore = new Store({portName: 'MyStore'});

//----------------------------------
// Initialisation code... check page type and add in the required components...

for(var i=0;i<3;i++) {
  const anchor = document.createElement('div');
  const id = 'unique-anchor-'+i;
  anchor.id = id;
  document.body.insertBefore(anchor, document.body.childNodes[0]);

  render(
      <Provider store={proxyStore}>
         <MyComponent uniqueNumber={i}/>
      </Provider>
       , document.getElementById(id)
   );
}

console.log('DONE!!!');
```

I'm closing this as I feel it's enough to help anyone else get started - feel free to re-open if you wish to comment / contribute.

**Comment by vhmth** [comment]
@Techdojo glad you figured this out. We do the same thing for a lot of our UI where it's the same component being rendered over and over and being inserted into various places in the DOM.
