### ISSUE TITLE
Advice on firing an async request to initialise the background page

### ISSUE THREAD

**Issue by Techdojo** [tshaddix/react-chrome-redux#81]
The question I have is can someone provide some guidance on the best practice on how to dispatch an action from the background page to initialise my store.

I've created a number of alias'd actions in my middleware so that UI interaction can trigger background actions (which can then dispatch other actions by using redux-thunk) however this only works when the UI popup is triggered.

What I want to do is fire off an async action (using axios) to download some initial data when the background page runs so I can initialise my store - ideally I'd like to call the `dispatch()` function but I can't seem to find any point that it's in scope.

Anyone got any ideas?

**Comment by Techdojo** [comment]
Ok - so I feel a little dumb at this point as all I had to do was call `store.dispatch()` from `background/index.js` however (again) I'll close this and leave it here so hopefully someone else might find this if needed! :)

**Comment by vhmth** [comment]
Yep - as with normal redux, you just need to dispatch against the store. :-)

Glad you figured it out @Techdojo
