### ISSUE TITLE
[Question] When using aliases needs to be a object?

### ISSUE THREAD

**Issue by jdinartejesus** [tshaddix/react-chrome-redux#84]
I need to use a function in aliases since I'm integrating w/ Firebase and I needed to add new task to Firebase before update the state. But since all the actions need to be an object I can or it's this wrong?

```
const aliases = {
  'CREATE_NEW_TASK': () => {
    console.log('Hello')
  }
}

export default createStore(
  tasksReducer,
  applyMiddleware(alias(aliases))
)

dispatch({ type: 'CREATE_NEW_TASK' })
```

`Error: Actions must be plain objects. Use custom middleware for async actions.`
`error dispatching result: Actions must be plain objects. Use custom middleware for async actions`

**Comment by tshaddix** [comment]
@jdinartejesus Got it. So you're waiting for a response from firebase before updating the state? If so, you are attempting an [Async Action](http://redux.js.org/docs/advanced/AsyncActions.html). You can use something like [redux-thunk](https://github.com/gaearon/redux-thunk) to handle these sorts of actions. Right now, you're using plain old redux without any middleware (other than alias) which means it's expecting an action object to be returned.

If you were to add something like `redux-thunk` to your middleware, you could return a function instead:

```js
const aliases = {
  'CREATE_NEW_TASK': () => {
    return (dispatch) => {
        // do your firebase work
        // when complete...
        return {
           type: 'CREATED_NEW_TASK',
           payload: someResponseFromFirebase
        };
    };
  }
}
```

It's important when doing these sort of aliases to rename your resulting actions into a new action name that is different from your aliased one. If you returned a new action named `CREATE_NEW_TASK`, it would just keep looping on itself as the alias fires its alias which fires its alias...

Does this help?

**Comment by jdinartejesus** [comment]
Thanks @tshaddix This actually helps a lot. Also I really appreciate your time on building this package.

**Comment by tshaddix** [comment]
@jdinartejesus No problem! Glad I could help :) 

This package is a result of all the awesome contributors such as yourself!
