### ISSUE TITLE
A package inspired by this package, Redux in Web worker for webapps!

### ISSUE THREAD

**Issue by sammkj** [tshaddix/react-chrome-redux#86]
While `react-chrome-redux` package has nothing to do with web workers but it holds similar concepts. I took this package and modified it, check it out [here](https://github.com/sammkj/workux). Any feedback is greatly welcomed!

**Comment by vhmth** [comment]
Woah this is very cool! Haven't had a ton of time to look at the code there just yet, but what have you been using this for @sammkj?

**Comment by sammkj** [comment]
We have a webapp that does lots of computation stuffs like reading QR codes, geolocation, etc.. Also, we're using Apollo and graphql to poll data. So we will be using `workux` to offload those tasks to web worker and leaving just the UI and animation stuffs on the main thread. No redux, no fetching data on the main thread. `workux` is currently still in experimental stage. We still have a few things on our todo list

**Comment by vhmth** [comment]
Very very cool @sammkj. Gonna be closing this, but keep up the great work. And thank you for linking to this repo in yours!
