### ISSUE TITLE
passing arguments to alias

### ISSUE THREAD

**Issue by Alino** [tshaddix/react-chrome-redux#88]
Hi, thank you for this project!
I would like to ask if we can pass args into aliases - can I do something like this?

aliases
```typescript
const aliases = {
    'SET_CURRENT_JOB_ALIAS': (action) => {
        return function(dispatch) {
            dispatch(SET_CURRENT_JOB(action.job));
        }
    }
};
```

content script
```typescript
store.dispatch({ type: 'SET_CURRENT_JOB_ALIAS', job: j });
```

**Comment by tshaddix** [comment]
Hi there! Yes - that's exactly what you can do. The alias will receive the original action as the first argument.
