### ISSUE TITLE
Error Help: dispatch-- value in _ref2 is undefined

### ISSUE THREAD

**Issue by fbessez** [tshaddix/react-chrome-redux#89]
Error in event handler for (unknown): TypeError: Cannot read property 'payload' of undefined

I am calling dispatch, but I am getting the above error whenever I get to my dispatch call. The _ref2 that is being given to the callback is simply {error: null} (no 'value' key), so it can't resolve `value.payload`. What might I be doing wrong? 

The correct data is being passed INTO the dispatch call in the form: `Object {type: "TYPENAME", trackerDelta: Object, connection: Object}`

Any ideas as to what might be the issue?

Thank you!

P.S. I am using react-chrome-redux 0.0.7, react 0.14.3, and redux 3.4.0

**Comment by tshaddix** [comment]
Hello! 

I think I know what's going on here. `react-chrome-redux` is expecting that you use the classic `redux` action shape which is of the form `{type: string, payload: object}`. If you wrap your `trackerDelta` and `connection` objects under a `payload` key, does everything work out?

**Comment by fbessez** [comment]
Hey @tshaddix , thanks for the quick response. Unfortunately, this did not seem to work.  Any other ideas?

**Comment by vhmth** [comment]
@fbessez is this happening on the background script? If so, could you try adding [redux-thunk](https://github.com/gaearon/redux-thunk) as a middleware to your store? I have a suspicion that will fix it.

**Comment by tshaddix** [comment]
Closing for now. Feel free to reopen @fbessez
