### ISSUE TITLE
Other good examples?

### ISSUE THREAD

**Issue by fxsloker** [tshaddix/react-chrome-redux#91]
Are there any examples of extensions with this utility except for those simplest extensions in the react-chrome-redux-examples? Maybe there is a big project? I'm newbie, so I don't know where to move after those simple examples. I want to see it in real practice.

**Comment by tshaddix** [comment]
Great question! I have a more complex extension [here](https://github.com/tshaddix/next-read) that I did as a fun little side project awhile ago.

**Comment by fxsloker** [comment]
@tshaddix Thank you. I will learn it.

**Comment by vhmth** [comment]
Hey @fxsloker you should be able to look at any other more complex example that uses something like [redux-thunk](https://github.com/gaearon/redux-thunk) as a good example of a complex redux app. There really isn't anything super complicated/different happening with this library that would bar you from learning how to use it. It's simply another way to think about Redux in the context of Chrome extension development.

I would if I could, but, to give you an example of a much more complicated extension built with react-chrome-redux, take a look at [Loom](https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb).
