### ISSUE TITLE
Issue using aliases

### ISSUE THREAD

**Issue by loyalty-company** [tshaddix/react-chrome-redux#92]
Hi, thanks for this beautifil work. Thanks to that I could start using React for my first chrome extension.
Though I've got some issues using aliases.

I followed your example because I need to fetch data from API and I need actions that can be used from content and from popup. But I can't make it work. Event with a simple exemple like this 
`export const aliases = {
  // this key is the name of the action to proxy, the value is the action
  // creator that gets executed when the proxied action is received in the
  // background
  'user-clicked-alias': () => {
    // this call can only be made in the background script
    console.log("start");
  }
}`

and a index.js like this 
`const store = createStore(
  rootReducer,
  applyMiddleware(
    alias(aliases)
  ));`

Everything compiled succesfully, my extension is loaded by chrome but if I want to dispatch event like before (even the ones for reducers) I got an error like this on the content page

> Error in event handler for (unknown): TypeError: Cannot read property 'error' of undefined

and error like this on background page

> Error in event handler for runtime.onMessage: TypeError: Cannot read property 'ADD_INSTANCE' of undefined
    at Object.dispatch

is that a known case ? Do I have to use a separate store for actions ? is that the good way to gather API calls ?

Thanks in advance

**Comment by tshaddix** [comment]
Hi there @loyalty-company !

Your `aliases` need to return a new action if you are going to use them:

```js
export const aliases = {
   'user-clicked-alias': () => {
        console.log("start");
        return { type: "Hello", payload: "World"};
    }
}
```
