### ISSUE TITLE
How to use popup.js and content.js in my chrome extension ?

### ISSUE THREAD

**Issue by 10S10** [tshaddix/react-chrome-redux#93]
I have file for content.js which is actually contains Whole UI of the Extension. 
This is Code Snippet 

```
import React from 'react';
import ReactDOM from 'react-dom';
import AppClass from '../../app/index';
import { Provider } from 'react-redux';
import { Store } from 'react-chrome-redux';

const store = new Store({ state: {}, portName: 'TAB_STORE' });

store.ready().then(() => {
  ReactDOM.render(
    <Provider store={store}>
      <AppClass />
    </Provider>,
        document.querySelector('#root')
    );
});
```

Another File is popup.js . 
If I write the following code in my popup.js file then Chrome console gives me error as 
Failed to load resource: the server responded with a status of 404 (Not Found) popup.bundle.js 

Following code I am including in popup.js 

```
import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
		<button> POPUP </button>
		,   document.querySelector('#app')
);
```

My issue is I actually don't get what should i write in my popup.js. 

As I am using boilerplate example so that automatically converts .js in to .html in chrome Folder.

Please help me I am stuck in this issue from last 5 days.

Thanks in advance.

**Comment by vhmth** [comment]
@10S10 do you have your code somewhere in a repo so we can check it out? It seems like you're referencing a file for your popup page that doesn't exist/can't be built.

**Comment by 10S10** [comment]
@vhmth Thanks For reply. 
You actually got my problem. 
Here issue is i can open popup but popup is not contained what i have written in popup.js render method. 

``` import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(
		<button> POPUP </button>
		,   document.querySelector('#app')
); 
```

I got the file as popup.bundle.html  but i am not getting the popup.bundle.js

**Comment by vhmth** [comment]
It would be helpful to see the code because I don't know how you're referencing `popup.bundle.js`. It depends on how you're including that in `popup.html.js`. Sometimes this can be a build-system thing, sometimes a messed up path, the code itself would make this easy. You can get rid of all of the code you don't wanna show, but `manifest.json`, your build scripts, and the popup assets would be useful.

**Comment by 10S10** [comment]
@vhmth Thanks for concerned . 

In my Project Actually i didn't mentioned the popup.js in entry point of script which is actually make bundle.js based on html. 

So I resolved my issue .
Thanks for help :)

**Comment by vhmth** [comment]
Ah I see! Glad you figured it out!
