### ISSUE TITLE
Get response in content script after request in background script

### ISSUE THREAD

**Issue by fxsloker** [tshaddix/react-chrome-redux#95]
Maybe the question will turn out to be stupid, but how to return the response code back to the content script without any changes to the store after a request to the server in background script?

Action:
```javascript
return (dispatch, getState) => {
   return fetch(<url>,
            {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    <some info>
                })
            })
            .then(handleErrors)
            .then(response => response.json())
            .then(response => {
                return Promise.resolve({
                    type: "test",
                    payload: response.status
                });
            })
            .catch(error => {
                return Promise.resolve({
                    type: "test",
                    payload: error
                });
            });
}
```

Content script:
```javascript
this.props.dispatch({
            type: "CREATE_SINGLE_POST",
            payload: {
                <some info>
            }
        })
            .then(res => {
                console.log(res);
            }).catch(err => {
                console.log(err);
        })
```

In content script I get empty object {}.

I just need to make a request in background script and get back the result in content script.

**Comment by vhmth** [comment]
Hi @fxsloker are you calling that Action creator on the background via [aliases](https://github.com/tshaddix/react-chrome-redux#3-optional-implement-actions-whose-logic-only-happens-in-the-background-script-we-call-them-aliases)? If you are executing that logic in the background script, I would definitely advocate for updating the store state so all of your content scripts will get the same consistent state (that's the point of this library).

If you do want to just signal to the background, you can use normal Chrome [message passing](https://developer.chrome.com/extensions/messaging).

**Comment by fxsloker** [comment]
Hey @vhmth yes, I am using aliases. I decided to update the store state after all.

 I considered [Action Responses](https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage#action-responses) which didn't work for me. Can you give me an example on dispatchResponder?

**Comment by vhmth** [comment]
Deferring to @tshaddix here on the `dispatchResponder`.

**Comment by tshaddix** [comment]
Whoops totally missed this tag. Super my bad. You can check out the `promiseResponder` we use by default [here](https://github.com/tshaddix/react-chrome-redux/blob/master/src/wrap-store/wrapStore.js#L15)

Sounds like your current solution is a good one (updating store state). That's how I do these sort of things. I'm going to answer the question as if you had not figured out what you wanted to do yet.

The dispatch responder is just a middleman function that takes whatever `dispatch` returns and crops it into the format `{value, error}` which is how RCR communicates between the background store and the ui pages. You could have a responder that looks for some field on the returned dispatch value that indicates the response code and then throw that on to the returned "error" or "value" field somewhere.
