### ISSUE TITLE
Keep Object References Through Serialization

### ISSUE THREAD

**Issue by jdolle** [tshaddix/react-chrome-redux#98]
There is no mention of objects being serialized from the background store to the content store. I was incredibly confused by my equality check in `componentWillReceiveProps` showing props were not equal even though they were.

The serialization should be documented and/or there should be a way to keep the object references. 
I had expected this store to behave just like a redux store.

**Comment by tshaddix** [comment]
Hi @jdolle  - sorry you ran into some trouble.

This is because of the limitations of the [chrome message api](https://developer.chrome.com/apps/messaging), which serializes messages before sending between the content-scripts and the event page. We can definitely add a note somewhere in the documentation.

Just curious: What's the use case of using the equality check in `componentWillReceiveProps`?

**Comment by jdolle** [comment]
A simplified version of what I'm doing is setting the extension's icon based on if the current location is within an array fetched from an API.
I made an alias that sets the icon on the background script and without a comparison check, it dispatches to set the icon, this causes `mapStateToProps` to fire, and that triggers `componentWillReceiveProps`, which fires the dispatch again -- so it loops endlessly.

**Comment by vhmth** [comment]
@tshaddix partial updates from the background script to the content scripts would help here, but then you have to answer the question of "what got updated?", which is pretty anti-redux. We'd end up having to either do checking on our end or have folks implement some weird API to signal what to send back (yuck).

I think the best option here is to document.

**Comment by jdolle** [comment]
I am worried about the inefficiency of passing everything every time.

Not only does it require more specific checks (checking IDs or some other value instead of reference) but also that is potentially a lot of data. What if mapStateToProps could be moved to the background -- allowing it to efficiently compare props on the background using references, then somehow (batched messaging targeting specific props of specific components somehow -- not entirely sure of implementation) update the appropriate components' props.

**Comment by jdolle** [comment]
^ Partial updates were easier than I anticipated.

@vhmth I don't understand why this is anti-redux. This is how redux behaves normally. Every time you dispatch an action it doesn't create a copy of the entire state.

**Comment by timkendall** [comment]
I'm not worried about this being _anti-redux_ as we are already extending that concept to get stores synchronized across processes. 

This change will actually bring behavior closer in line with how canonical Redux works.  As @jdolle mentioned, behavior will now be what is expected if one wasn't using this library 👍 

It's actually a pretty spicy idea that reminds me of how running React in a Worker works - we just send the minimal "patch" to update our "virtual store" in a different process :)

I'm all for this!

**Comment by vhmth** [comment]
https://www.useloom.com/share/74178d993c6e4e9fab0f2a6ed5b47777
